<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Capítulo 2 ETL con Tidyverse | Visualización de datos en R</title>
  <meta name="description" content="Notas de clase de dataviz" />
  <meta name="generator" content="bookdown 0.43 and GitBook 2.6.7" />

  <meta property="og:title" content="Capítulo 2 ETL con Tidyverse | Visualización de datos en R" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Notas de clase de dataviz" />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capítulo 2 ETL con Tidyverse | Visualización de datos en R" />
  
  <meta name="twitter:description" content="Notas de clase de dataviz" />
  

<meta name="author" content="Carlos de Oro Aguado" />


<meta name="date" content="2025-09-05" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="intro.html"/>
<link rel="next" href="vizestatico.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/codefolding-lua-1.1/codefolding-lua.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Visualización de datos en R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Asignatura</a>
<ul>
<li class="chapter" data-level="" data-path=""><a href="#justificaci%C3%B3n"><i class="fa fa-check"></i>Justificación</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#objetivo-general-de-la-asignatura"><i class="fa fa-check"></i>Objetivo general de la asignatura</a></li>
<li class="chapter" data-level="" data-path=""><a href="#resultados-de-aprendizaje-objetivos-espec%C3%ADficos"><i class="fa fa-check"></i>Resultados de aprendizaje (Objetivos específicos)</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#temas-de-la-asignatura"><i class="fa fa-check"></i>Temas de la asignatura</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>1</b> Introducción</a>
<ul>
<li class="chapter" data-level="1.1" data-path="02-etltidyverse.html"><a href="#introducci%C3%B3n-a-r-y-rstudio"><i class="fa fa-check"></i><b>1.1</b> Introducción a R y RStudio</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="02-etltidyverse.html"><a href="#qu%C3%A9-es-r"><i class="fa fa-check"></i><b>1.1.1</b> ¿Qué es R?</a></li>
<li class="chapter" data-level="1.1.2" data-path="02-etltidyverse.html"><a href="#qu%C3%A9-es-rstudio"><i class="fa fa-check"></i><b>1.1.2</b> ¿Qué es RStudio?</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="02-etltidyverse.html"><a href="#introducci%C3%B3n-a-git-y-github"><i class="fa fa-check"></i><b>1.2</b> Introducción a Git y GitHub</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="02-etltidyverse.html"><a href="#qu%C3%A9-es-git"><i class="fa fa-check"></i><b>1.2.1</b> ¿Qué es Git?</a></li>
<li class="chapter" data-level="1.2.2" data-path="02-etltidyverse.html"><a href="#qu%C3%A9-es-github"><i class="fa fa-check"></i><b>1.2.2</b> ¿Qué es GitHub?</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="intro.html"><a href="intro.html#pasos-para-publicar-un-libro-bookdown-en-github-pages"><i class="fa fa-check"></i><b>1.3</b> Pasos para publicar un libro <code>bookdown</code> en GitHub Pages</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="02-etltidyverse.html"><a href="#video-paso-a-paso-de-la-publicaci%C3%B3n-del-libro-en-github-pages"><i class="fa fa-check"></i><b>1.3.1</b> Video paso a paso de la publicación del libro en GitHub Pages</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="etltidyverse.html"><a href="etltidyverse.html"><i class="fa fa-check"></i><b>2</b> ETL con Tidyverse</a>
<ul>
<li class="chapter" data-level="2.1" data-path="etltidyverse.html"><a href="etltidyverse.html#data-frames"><i class="fa fa-check"></i><b>2.1</b> Data Frames</a></li>
<li class="chapter" data-level="2.2" data-path="02-etltidyverse.html"><a href="#importaci%C3%B3n-de-datos"><i class="fa fa-check"></i><b>2.2</b> Importación de datos</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="02-etltidyverse.html"><a href="#importaci%C3%B3n-de-archivos-csv-con-read.table"><i class="fa fa-check"></i><b>2.2.1</b> Importación de archivos <code>csv</code> con <code>read.table()</code></a></li>
<li class="chapter" data-level="2.2.2" data-path="02-etltidyverse.html"><a href="#importaci%C3%B3n-de-archivos-txt-delimitados-por-tabulaci%C3%B3n-con-read.table"><i class="fa fa-check"></i><b>2.2.2</b> Importación de archivos <code>txt</code> delimitados por tabulación con <code>read.table()</code></a></li>
<li class="chapter" data-level="2.2.3" data-path="02-etltidyverse.html"><a href="#importaci%C3%B3n-de-archivos-csv-con-read.csv"><i class="fa fa-check"></i><b>2.2.3</b> Importación de archivos <code>csv</code> con <code>read.csv()</code></a></li>
<li class="chapter" data-level="2.2.4" data-path="etltidyverse.html"><a href="etltidyverse.html#uso-de-readr-de-tidyverse"><i class="fa fa-check"></i><b>2.2.4</b> Uso de <code>readr</code> de tidyverse</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="02-etltidyverse.html"><a href="#transformaci%C3%B3n-de-datos"><i class="fa fa-check"></i><b>2.3</b> Transformación de datos</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="etltidyverse.html"><a href="etltidyverse.html#el-paquete-dplyr"><i class="fa fa-check"></i><b>2.3.1</b> El paquete <code>dplyr</code></a></li>
<li class="chapter" data-level="2.3.2" data-path="etltidyverse.html"><a href="etltidyverse.html#operador"><i class="fa fa-check"></i><b>2.3.2</b> Operador <code>%&gt;%</code></a></li>
<li class="chapter" data-level="2.3.3" data-path="etltidyverse.html"><a href="etltidyverse.html#filtrar-datos-para-crear-un-subconjunto"><i class="fa fa-check"></i><b>2.3.3</b> Filtrar datos para crear un subconjunto</a></li>
<li class="chapter" data-level="2.3.4" data-path="etltidyverse.html"><a href="etltidyverse.html#acotar-la-lista-de-columnas-con-select"><i class="fa fa-check"></i><b>2.3.4</b> Acotar la lista de columnas con <code>select()</code></a></li>
<li class="chapter" data-level="2.3.5" data-path="etltidyverse.html"><a href="etltidyverse.html#organizar-las-filas"><i class="fa fa-check"></i><b>2.3.5</b> Organizar las filas</a></li>
<li class="chapter" data-level="2.3.6" data-path="02-etltidyverse.html"><a href="#a%C3%B1adir-columnas-con-mutate"><i class="fa fa-check"></i><b>2.3.6</b> Añadir columnas con <code>mutate</code></a></li>
<li class="chapter" data-level="2.3.7" data-path="02-etltidyverse.html"><a href="#agrupaci%C3%B3n-y-resumen-de-los-datos"><i class="fa fa-check"></i><b>2.3.7</b> Agrupación y resumen de los datos</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="02-etltidyverse.html"><a href="#ordenaci%C3%B3n-de-datos"><i class="fa fa-check"></i><b>2.4</b> Ordenación de datos</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="02-etltidyverse.html"><a href="#recopilaci%C3%B3n"><i class="fa fa-check"></i><b>2.4.1</b> Recopilación</a></li>
<li class="chapter" data-level="2.4.2" data-path="02-etltidyverse.html"><a href="#distribuci%C3%B3n"><i class="fa fa-check"></i><b>2.4.2</b> Distribución</a></li>
<li class="chapter" data-level="2.4.3" data-path="02-etltidyverse.html"><a href="#separaci%C3%B3n"><i class="fa fa-check"></i><b>2.4.3</b> Separación</a></li>
<li class="chapter" data-level="2.4.4" data-path="02-etltidyverse.html"><a href="#uni%C3%B3n"><i class="fa fa-check"></i><b>2.4.4</b> Unión</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="vizestatico.html"><a href="vizestatico.html"><i class="fa fa-check"></i><b>3</b> Exploración y visualización estática de datos</a>
<ul>
<li class="chapter" data-level="3.1" data-path="02-etltidyverse.html"><a href="#visualizaci%C3%B3n-de-variables-categ%C3%B3ricas-con-gr%C3%A1ficos-de-barras"><i class="fa fa-check"></i><b>3.1</b> Visualización de variables categóricas con gráficos de barras</a></li>
<li class="chapter" data-level="3.2" data-path="02-etltidyverse.html"><a href="#visualizaci%C3%B3n-de-variable-continua-con-un-histograma"><i class="fa fa-check"></i><b>3.2</b> Visualización de variable continua con un histograma</a></li>
<li class="chapter" data-level="3.3" data-path="02-etltidyverse.html"><a href="#visualizaci%C3%B3n-de-la-covariaci%C3%B3n-con-gr%C3%A1ficos-de-caja"><i class="fa fa-check"></i><b>3.3</b> Visualización de la covariación con gráficos de caja</a></li>
<li class="chapter" data-level="3.4" data-path="02-etltidyverse.html"><a href="#visualizaci%C3%B3n-de-la-covariaci%C3%B3n-con-el-gr%C3%A1fico-de-burbuja"><i class="fa fa-check"></i><b>3.4</b> Visualización de la covariación con el gráfico de burbuja</a></li>
<li class="chapter" data-level="3.5" data-path="02-etltidyverse.html"><a href="#visualizaci%C3%B3n-2d-de-contenedores-y-hex%C3%A1gonos"><i class="fa fa-check"></i><b>3.5</b> Visualización 2D de contenedores y hexágonos</a></li>
<li class="chapter" data-level="3.6" data-path="02-etltidyverse.html"><a href="#visualizaci%C3%B3n-de-estad%C3%ADsticas-resumen-de-los-datos"><i class="fa fa-check"></i><b>3.6</b> Visualización de estadísticas ( resumen de los datos)</a></li>
<li class="chapter" data-level="3.7" data-path="02-etltidyverse.html"><a href="#visualizaci%C3%B3n-de-un-gr%C3%A1fico-de-correlaci%C3%B3n"><i class="fa fa-check"></i><b>3.7</b> Visualización de un gráfico de correlación</a></li>
<li class="chapter" data-level="3.8" data-path="02-etltidyverse.html"><a href="#visualizaci%C3%B3n-de-un-gr%C3%A1fico-de-dispersi%C3%B3n"><i class="fa fa-check"></i><b>3.8</b> Visualización de un gráfico de dispersión</a></li>
<li class="chapter" data-level="3.9" data-path="02-etltidyverse.html"><a href="#visualizaci%C3%B3n-del-gr%C3%A1fico-de-dispersi%C3%B3n-con-linea-de-tendencia"><i class="fa fa-check"></i><b>3.9</b> Visualización del gráfico de dispersión con linea de tendencia</a></li>
<li class="chapter" data-level="3.10" data-path="02-etltidyverse.html"><a href="#visualizaci%C3%B3n-de-trazado-de-categor%C3%ADas"><i class="fa fa-check"></i><b>3.10</b> Visualización de trazado de categorías</a></li>
<li class="chapter" data-level="3.11" data-path="vizestatico.html"><a href="vizestatico.html#visualizacion-etiquetando-nombres"><i class="fa fa-check"></i><b>3.11</b> Visualizacion etiquetando nombres</a></li>
<li class="chapter" data-level="3.12" data-path="02-etltidyverse.html"><a href="#visualizaci%C3%B3n-de-leyendas"><i class="fa fa-check"></i><b>3.12</b> Visualización de leyendas</a></li>
<li class="chapter" data-level="3.13" data-path="02-etltidyverse.html"><a href="#visualiazci%C3%B3n-con-facetas"><i class="fa fa-check"></i><b>3.13</b> Visualiazción con facetas</a></li>
<li class="chapter" data-level="3.14" data-path="02-etltidyverse.html"><a href="#visualizaci%C3%B3n-de-tramas-de-viol%C3%ADn"><i class="fa fa-check"></i><b>3.14</b> Visualización de tramas de violín</a></li>
<li class="chapter" data-level="3.15" data-path="02-etltidyverse.html"><a href="#visualizaci%C3%B3n-de-gr%C3%A1ficos-de-densidad"><i class="fa fa-check"></i><b>3.15</b> Visualización de gráficos de densidad</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="ggmap.html"><a href="ggmap.html"><i class="fa fa-check"></i><b>4</b> Visualización de datos geográficos con ggmap</a>
<ul>
<li class="chapter" data-level="4.1" data-path="ggmap.html"><a href="ggmap.html#paquete-ggmap"><i class="fa fa-check"></i><b>4.1</b> Paquete <code>ggmap</code></a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="ggmap.html"><a href="ggmap.html#funciones-principales-de-ggmap"><i class="fa fa-check"></i><b>4.1.1</b> Funciones principales de <code>ggmap</code></a></li>
<li class="chapter" data-level="4.1.2" data-path="02-etltidyverse.html"><a href="#relaci%C3%B3n-con-ggplot2"><i class="fa fa-check"></i><b>4.1.2</b> Relación con <code>ggplot2</code></a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="02-etltidyverse.html"><a href="#construcci%C3%B3n-de-un-mapa-base"><i class="fa fa-check"></i><b>4.2</b> Construcción de un mapa base</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="referencias.html"><a href="referencias.html"><i class="fa fa-check"></i>Referencias</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Publicado con bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Visualización de datos en R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="etltidyverse" class="section level1 hasAnchor" number="2">
<h1><span class="header-section-number">Capítulo 2</span> ETL con Tidyverse<a href="etltidyverse.html#etltidyverse" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>El <strong>Tidyverse</strong> es un conjunto de paquetes integrados para el lenguaje de programación R, diseñados con el objetivo de facilitar el análisis de datos de manera estructurada, legible y eficiente. Su filosofía se basa en el concepto de <strong>“datos ordenados” (tidy data)</strong>, donde cada variable es una columna, cada observación una fila, y cada tipo de unidad observacional forma una tabla.</p>
<p>Estos paquetes comparten principios de diseño comunes y una gramática coherente, lo que permite a los usuarios aprender un conjunto de reglas aplicables en todo el ecosistema, aumentando así la productividad y la claridad del código.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:tidy-fig"></span>
<img src="images/tidypacsinfondo.png" alt="Paquetes de tidyverse" width="70%" />
<p class="caption">
Figura 2.1: Paquetes de tidyverse
</p>
</div>
<div id="data-frames" class="section level2 hasAnchor" number="2.1">
<h2><span class="header-section-number">2.1</span> Data Frames<a href="etltidyverse.html#data-frames" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="admon-box definicion">
<div class="admon-title">
<span class="icon"></span> Definición
</div>
<p>
Un <strong>data frame</strong> es una estructura de datos clave en estadística y en <strong>R</strong>.
</p>
</div>
<ul>
<li>La estructura básica de un data frame es que <em>hay una observación por fila y cada columna representa una variable, medida, rasgo o característica de esa observación</em>.<br />
</li>
<li><strong>R</strong> tiene una implementación interna de los data frames que probablemente es la que más se utiliza en la práctica.</li>
</ul>
</div>
<div id="importación-de-datos" class="section level2 hasAnchor" number="2.2">
<h2><span class="header-section-number">2.2</span> Importación de datos<a href="#importaci%C3%B3n-de-datos" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="admon-box nota">
<div class="admon-title">
<span class="icon"></span> Fuentes de datos en R
</div>
<p>
Los conjuntos de datos de gran tamaño, generalmente almacenados como <strong>data frames</strong> en <strong>R</strong>, suelen provenir de archivos externos.<br />
Existen múltiples tipos de archivos que pueden importarse, entre ellos:<br />

</p>
<ul>
<li>
<strong>Archivos de texto</strong> en formatos como <code>csv</code>, <code>txt</code>, <code>html</code> y <code>json</code>.
</li>
<li>
Salidas de software estadístico como <strong>SAS</strong> y <strong>SPSS</strong>.
</li>
<li>
Recursos en línea como páginas <strong>html</strong> y servicios web.
</li>
<li>
<strong>Bases de datos relacionales y no relacionales</strong>.
</li>
</ul>
<p>
El ecosistema <strong>Tidyverse</strong> ofrece funciones que permiten importar y gestionar estas diversas fuentes de datos de manera sencilla y eficiente.
</p>
</div>
<div id="importación-de-archivos-csv-con-read.table" class="section level3 hasAnchor" number="2.2.1">
<h3><span class="header-section-number">2.2.1</span> Importación de archivos <code>csv</code> con <code>read.table()</code><a href="#importaci%C3%B3n-de-archivos-csv-con-read.table" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="admon-box definicion">
<div class="admon-title">
<span class="icon"></span> Definición
</div>
<p>
La función <code>read.table()</code> es una función integrada en <strong>R</strong> que permite leer archivos de distintos formatos y convertirlos en un <strong>data frame</strong>.<br />
Es una de las funciones más utilizadas para importar archivos simples en R.
</p>
</div>
<p>La sintaxis de <strong><code>read.table()</code></strong> requiere indicar:<br />
- Un nombre de archivo (ruta de acceso).<br />
- Un valor lógico (<strong><code>TRUE/FALSE</code></strong>) para definir si la primera fila contiene los nombres de las columnas.</p>
<ul>
<li>Si se establece en <strong><code>TRUE</code></strong>, la primera fila se interpreta como encabezado.<br />
</li>
<li>Si se establece en <strong><code>FALSE</code></strong>, las columnas se importan sin nombres definidos.</li>
</ul>
<p>El resultado de la función siempre es un <strong>data frame</strong>.</p>
<p>Una alternativa práctica es la función <strong><code>file.choose()</code></strong>, que permite seleccionar el archivo de manera interactiva sin necesidad de escribir la ruta manualmente.</p>
<div class="admon-box observacion">
<div class="admon-title">
<span class="icon"></span> Observación
</div>
<p>
Pasos para importar un archivo <code>csv</code> con <code>read.table()</code>:
</p>
<ol>
<li>
Abrir <strong>RStudio</strong> y dirigirse a la consola.
</li>
<li>
Establecer el directorio de trabajo con código en la consola o desde el menú:<br>
<em>Sesión → Establecer directorio de trabajo → Elegir directorio</em>.
</li>
<li>
Ejecutar la función <code>read.table()</code> indicando el archivo <code>csv</code> a importar.
</li>
</ol>
</div>
<details class=chunk-details open><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="etltidyverse.html#cb1-1" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">&quot;~/Books_CienciaDatos/rbook_dataviz&quot;</span>)</span></code></pre></div>
</details>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:fig-2"></span>
<img src="images/setwd.png" alt="setwd" width="70%" />
<p class="caption">
Figura 2.2: setwd
</p>
</div>
<ul>
<li><p>En la carpeta <strong><a href="https://github.com/cdeoroaguado/Datos/blob/main/datarstudio/RDataSets.zip">RDataSets</a></strong> se encuentra el archivo <strong>StudyArea.csv</strong>, que corresponde a un archivo separado por comas.<br />
Este archivo contiene información sobre incendios forestales ocurridos entre los años 1980 y 2016 en distintos estados de EE. UU., entre ellos: California, Oregón, Washington, Idaho, Montana, Wyoming, Colorado, Utah, Nevada, Arizona y Nuevo México.</p></li>
<li><p>El archivo incluye más de <strong>439000 registros</strong> distribuidos en <strong>37 columnas</strong>, que describen las características de cada incendio durante ese periodo.</p></li>
<li><p>Para cargar estos datos en un nuevo objeto <strong>data frame</strong>, puede utilizarse la función <code>read.table()</code> de la siguiente manera:</p></li>
</ul>
<details class=chunk-details open><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="etltidyverse.html#cb2-1" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">&quot;data/StudyArea.csv&quot;</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
</details>
<ul>
<li>Recibirá un mensaje de error cuando intente ejecutar esta línea de código. El mensaje de error mensaje de error debería aparecer como se ve a continuación</li>
</ul>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:fig-3"></span>
<img src="images/error.png" alt="error en rmd" width="70%" />
<p class="caption">
Figura 2.3: error en rmd
</p>
</div>
<ul>
<li>La razón por la que se generó un mensaje de error en este caso es que la función <strong><code>read.table()</code></strong> utiliza espacios como delimitador entre registros y nuestro archivo utiliza comas como delimitador</li>
</ul>
<p>Actualice su llamada a <strong><code>read.table()</code></strong> como se ve a continuación para incluir el argumento <strong><code>sep</code></strong>, que debería ser una coma</p>
<details class=chunk-details open><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="etltidyverse.html#cb3-1" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">&quot;data/StudyArea.csv&quot;</span>, <span class="at">sep=</span><span class="st">&quot;,&quot;</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
</details>
<ul>
<li>Cuando ejecute esta línea de código verá un nuevo error</li>
</ul>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:fig-4"></span>
<img src="images/error2.png" alt="continuación del error en rmd" width="70%" />
<p class="caption">
Figura 2.4: continuación del error en rmd
</p>
</div>
<ul>
<li>La función <code>read.table()</code> no completa de manera automática las celdas vacías con un valor por defecto como <code>NA</code>.<br />
Por este motivo, si alguna fila del archivo no contiene el número esperado de columnas (en este caso, 14), se genera un mensaje de error durante la importación.</li>
</ul>
<p>Para solucionar este inconveniente, puede añadirse el parámetro <code>fill = TRUE</code>, lo que permite a <strong>R</strong> rellenar los espacios vacíos con <code>NA</code> y mantener la estructura correcta del <code>data.frame</code>.</p>
<details class=chunk-details open><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="etltidyverse.html#cb4-1" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">&quot;data/StudyArea.csv&quot;</span>, </span>
<span id="cb4-2"><a href="etltidyverse.html#cb4-2" tabindex="-1"></a>                 <span class="at">header =</span> <span class="cn">TRUE</span>, </span>
<span id="cb4-3"><a href="etltidyverse.html#cb4-3" tabindex="-1"></a>                 <span class="at">fill   =</span> <span class="cn">TRUE</span>, </span>
<span id="cb4-4"><a href="etltidyverse.html#cb4-4" tabindex="-1"></a>                 <span class="at">sep    =</span> <span class="st">&quot;,&quot;</span>)</span>
<span id="cb4-5"><a href="etltidyverse.html#cb4-5" tabindex="-1"></a><span class="fu">nrow</span>(df)</span></code></pre></div>
</details>
<pre><code>## [1] 153095</code></pre>
<ul>
<li><p>Al ejecutar esta instrucción, el contenido del archivo se importa a un objeto de tipo <strong>data frame</strong>. Sin embargo, al revisar la pestaña <strong>Global Environment</strong> en <strong>RStudio</strong>, se observa que solo se han cargado <strong>153095 registros</strong>, a pesar de que el archivo original contiene más de <strong>400000</strong>.</p></li>
<li><p>La causa de esta diferencia suele estar en el manejo de las <strong>comillas (simples o dobles)</strong> presentes dentro del archivo <code>csv</code>, las cuales pueden interrumpir la lectura y provocar que algunos registros sean descartados.</p></li>
</ul>
<p>Para corregir este problema, se debe añadir el parámetro <code>quote = ""</code>, que le indica a <strong>R</strong> que ignore las comillas y procese correctamente todas las filas del archivo.</p>
<details class=chunk-details open><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="etltidyverse.html#cb6-1" tabindex="-1"></a>df <span class="ot">=</span> <span class="fu">read.table</span>(<span class="st">&quot;data/StudyArea.csv&quot;</span>, </span>
<span id="cb6-2"><a href="etltidyverse.html#cb6-2" tabindex="-1"></a>                <span class="at">header=</span><span class="cn">TRUE</span>, </span>
<span id="cb6-3"><a href="etltidyverse.html#cb6-3" tabindex="-1"></a>                <span class="at">fill=</span><span class="cn">TRUE</span>, </span>
<span id="cb6-4"><a href="etltidyverse.html#cb6-4" tabindex="-1"></a>                <span class="at">quote=</span><span class="st">&quot;</span><span class="sc">\&quot;</span><span class="st">&quot;</span>, </span>
<span id="cb6-5"><a href="etltidyverse.html#cb6-5" tabindex="-1"></a>                <span class="at">sep=</span><span class="st">&quot;,&quot;</span>)</span>
<span id="cb6-6"><a href="etltidyverse.html#cb6-6" tabindex="-1"></a><span class="fu">nrow</span>(df)</span></code></pre></div>
</details>
<pre><code>## [1] 439362</code></pre>
<ul>
<li>Al ejecutar esta línea de código, se deberían importar <strong>440476 registros</strong>. Los datos se cargan en un objeto de tipo <strong>R data.frame</strong>, que es una estructura similar a una tabla. Por ahora, puede pensarse en ellos como tablas que contienen columnas y filas.</li>
</ul>
<div class="admon-box observacion">
<div class="admon-title">
<span class="icon"></span> Observación
</div>
<p>
<p>La función <code>read.table()</code> se utiliza normalmente para cargar archivos de texto delimitados por tabulaciones.</p>
Sin embargo, muchas personas intentan emplearla directamente con archivos en formato <code>csv</code> sin especificar los parámetros adecuados, lo que puede generar errores en la importación.<br />
Una alternativa más práctica es usar la función <code>read.csv()</code>, como veremos en el siguiente paso.
</p>
</div>
</div>
<div id="importación-de-archivos-txt-delimitados-por-tabulación-con-read.table" class="section level3 hasAnchor" number="2.2.2">
<h3><span class="header-section-number">2.2.2</span> Importación de archivos <code>txt</code> delimitados por tabulación con <code>read.table()</code><a href="#importaci%C3%B3n-de-archivos-txt-delimitados-por-tabulaci%C3%B3n-con-read.table" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><p>La función <code>read.table()</code> se utiliza con frecuencia para leer el contenido de archivos delimitados por tabulaciones u otros separadores. En este ejemplo, se trabajará con el archivo <strong>all_genes_pombase.txt</strong>, ubicado en la carpeta <strong><a href="https://github.com/cdeoroaguado/Datos/blob/main/datarstudio/RDataSets.zip">RDataSets</a></strong>.</p></li>
<li><p>Antes de importarlo en <strong>R</strong>, se recomienda abrir el archivo en <strong>Excel</strong> o en cualquier editor de texto para observar su estructura, campos y delimitadores.</p></li>
<li><p>Una vez identificado el formato del archivo, en la consola de <strong>R</strong> puedes ejecutar el siguiente código para realizar la importación:</p></li>
</ul>
<details class=chunk-details open><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="etltidyverse.html#cb8-1" tabindex="-1"></a><span class="co"># Lectura de archivo delimitado por tabulaciones</span></span>
<span id="cb8-2"><a href="etltidyverse.html#cb8-2" tabindex="-1"></a>genes <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">&quot;data/all_genes_pombase.txt&quot;</span>, </span>
<span id="cb8-3"><a href="etltidyverse.html#cb8-3" tabindex="-1"></a>                    <span class="at">header =</span> <span class="cn">TRUE</span>,       </span>
<span id="cb8-4"><a href="etltidyverse.html#cb8-4" tabindex="-1"></a>                    <span class="at">sep =</span> <span class="st">&quot;</span><span class="sc">\t</span><span class="st">&quot;</span>,          </span>
<span id="cb8-5"><a href="etltidyverse.html#cb8-5" tabindex="-1"></a>                    <span class="at">quote=</span><span class="st">&quot;</span><span class="sc">\&quot;</span><span class="st">&quot;</span>)  </span>
<span id="cb8-6"><a href="etltidyverse.html#cb8-6" tabindex="-1"></a><span class="co"># numero de filas</span></span>
<span id="cb8-7"><a href="etltidyverse.html#cb8-7" tabindex="-1"></a><span class="fu">nrow</span>(genes)</span></code></pre></div>
</details>
<pre><code>## [1] 7019</code></pre>
<details class=chunk-details open><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="etltidyverse.html#cb10-1" tabindex="-1"></a><span class="co"># Visualizar las primeras filas</span></span>
<span id="cb10-2"><a href="etltidyverse.html#cb10-2" tabindex="-1"></a><span class="fu">head</span>(genes)</span></code></pre></div>
</details>
<pre><code>##     ensembl_id        name chromosome
## 1  SPAC1002.01 SPAC1002.01          I
## 2  SPAC1002.02       pom34          I
## 3 SPAC1002.03c        gls2          I
## 4 SPAC1002.04c       taf11          I
## 5 SPAC1002.05c        jmj2          I
## 6 SPAC1002.06c        bqt2          I
##                                                     description   feature_type
## 1                                     conserved fungal protein  protein_coding
## 2                                            nucleoporin Pom34  protein_coding
## 3                            glucosidase II alpha subunit Gls2  protein_coding
## 4 transcription factor TFIID complex subunit Taf11 (predicted)  protein_coding
## 5                                     histone demethylase Jmj2  protein_coding
## 6                               bouquet formation protein Bqt2  protein_coding
##   strand   start     end
## 1      1 1798347 1799015
## 2      1 1799061 1800053
## 3     -1 1799915 1803141
## 4     -1 1803624 1804491
## 5     -1 1804548 1806797
## 6     -1 1807270 1807781</code></pre>
<p>Esto permitirá cargar <strong>7019 registros</strong> en un objeto <code>data.frame</code>. Es importante tener en cuenta que, aunque la función realiza la importación, <strong>varios de sus parámetros deben configurarse adecuadamente al momento de leer el dataset</strong>, lo que hace que el proceso no sea tan directo ni automático como podría suponerse inicialmente.</p>
</div>
<div id="importación-de-archivos-csv-con-read.csv" class="section level3 hasAnchor" number="2.2.3">
<h3><span class="header-section-number">2.2.3</span> Importación de archivos <code>csv</code> con <code>read.csv()</code><a href="#importaci%C3%B3n-de-archivos-csv-con-read.csv" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="admon-box definicion">
<div class="admon-title">
<span class="icon"></span> Definición: <code>read.csv()</code>
</div>
<p>
La función <code>read.csv()</code> es una función incorporada en <strong>R</strong> que permite importar archivos delimitados por comas (<code>csv</code>) de manera sencilla.<br />
Está diseñada específicamente para este tipo de archivos y establece de forma predeterminada el argumento
<code>header = TRUE</code> (la primera fila se toma como nombres de columna) y <code>sep = “,”</code>
(coma como delimitador de campos).<br />
Esto hace que <code>read.csv()</code> sea una de las formas más rápidas y eficientes de cargar datos en <strong>R</strong> cuando provienen de archivos <code>csv</code>.
</p>
</div>
<ul>
<li><p>La función <code>read.csv()</code> es una función incorporada en <strong>R</strong> que resulta casi idéntica a <code>read.table()</code>. La principal diferencia es que en <code>read.csv()</code> los argumentos de <strong>cabecera</strong> y <strong>relleno</strong> se establecen en <code>TRUE</code> por defecto, lo que facilita la carga de archivos delimitados por comas (<code>csv</code>). En este punto, se observa que usar <code>read.csv()</code> implifica notablemente el proceso de importación.</p></li>
<li><p>A diferencia de <code>read.table()</code>, la función <code>read.csv()</code> <strong>gestiona automáticamente la mayoría de las configuraciones necesarias</strong> al leer un archivo <code>csv</code>. Esto permite cargar correctamente incluso archivos con más de <strong>400000 registros</strong> sin tener que especificar tantos parámetros manualmente.</p></li>
</ul>
<details class=chunk-details open><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="etltidyverse.html#cb12-1" tabindex="-1"></a><span class="co"># Lectura de archivo CSV con read.csv()</span></span>
<span id="cb12-2"><a href="etltidyverse.html#cb12-2" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;data/StudyArea.csv&quot;</span>)</span>
<span id="cb12-3"><a href="etltidyverse.html#cb12-3" tabindex="-1"></a></span>
<span id="cb12-4"><a href="etltidyverse.html#cb12-4" tabindex="-1"></a><span class="co"># numero de fila</span></span>
<span id="cb12-5"><a href="etltidyverse.html#cb12-5" tabindex="-1"></a><span class="fu">nrow</span>(df)</span></code></pre></div>
</details>
<pre><code>## [1] 439362</code></pre>
</div>
<div id="uso-de-readr-de-tidyverse" class="section level3 hasAnchor" number="2.2.4">
<h3><span class="header-section-number">2.2.4</span> Uso de <code>readr</code> de tidyverse<a href="etltidyverse.html#uso-de-readr-de-tidyverse" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="admon-box definicion">
<div class="admon-title">
<span class="icon"></span> Definición: <code>readr</code>
</div>
<p>
<code>readr</code> es el paquete del ecosistema <strong>tidyverse</strong> para lectura y escritura rápida de datos tabulares.
Produce objetos <code>tibble</code>, maneja de forma estable codificaciones (UTF-8), tipos de columna y valores perdidos, e
incluye herramientas para diagnosticar problemas de importación. Su API es consistente, minimalista y pensada para flujos
reproducibles.
</p>
</div>
<div class="admon-box ventaja">
<div class="admon-title">
<span class="icon"></span> Ventajas claves
</div>
<ol>
<li>
<strong>Velocidad y consistencia</strong> en lectura/escritura de archivos delimitados.
</li>
<li>
<strong>Tipos de columnas explícitos</strong> con <code>col_types</code> y funciones <code>col_*</code>.
</li>
<li>
<strong>Diagnóstico</strong> con <code>spec()</code> y <code>problems()</code>.
</li>
<li>
<strong>Salida en <code>tibble</code></strong> (imprime y maneja mejor columnas anchas/fechas).
</li>
<li>
<strong>Soporte de locales</strong> (<code>locale()</code>) para decimales, fechas, codificación, etc.
</li>
</ol>
</div>
<div class="admon-box observacion">
<div class="admon-title">
<span class="icon"></span> Funciones principales de lectura
</div>
<p>
<table>
<colgroup>
<col width="22%" />
<col width="43%" />
<col width="33%" />
</colgroup>
<thead>
<tr class="header">
<th>Función</th>
<th>Propósito</th>
<th>Formato/Delimitador</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>read_csv()</code></td>
<td><code>csv</code> con punto como decimal</td>
<td><code>,</code></td>
</tr>
<tr class="even">
<td><code>read_csv2()</code></td>
<td><code>csv</code> europeo (coma decimal)</td>
<td><code>;</code></td>
</tr>
<tr class="odd">
<td><code>read_tsv()</code></td>
<td>Valores separados por tabulador</td>
<td><code>\t</code></td>
</tr>
<tr class="even">
<td><code>read_delim(delim=)</code></td>
<td>Delimitador personalizado</td>
<td>Cualquiera (p. ej. <code>\|</code>, <code>:</code>)</td>
</tr>
<tr class="odd">
<td><code>read_table()</code></td>
<td>Columnas separadas por espacios</td>
<td>Espacios en blanco</td>
</tr>
<tr class="even">
<td><code>read_fwf()</code></td>
<td>Formato de ancho fijo</td>
<td>Anchos/posiciones</td>
</tr>
<tr class="odd">
<td><code>read_lines()</code></td>
<td>Leer líneas como vector de caracteres</td>
<td>Texto</td>
</tr>
<tr class="even">
<td><code>read_file()</code></td>
<td>Leer archivo completo como cadena única</td>
<td>Texto</td>
</tr>
<tr class="odd">
<td><code>read_rds()</code></td>
<td>Leer archivo R serializado</td>
<td><code>.rds</code></td>
</tr>
</tbody>
</table>
</p>
</div>
<div class="admon-box observacion">
<div class="admon-title">
<span class="icon"></span> Funciones de escritura
</div>
<p>
<table>
<thead>
<tr class="header">
<th>Función</th>
<th>Propósito</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>write_csv()</code></td>
<td>Escribir <code>csv</code> (punto decimal)</td>
</tr>
<tr class="even">
<td><code>write_csv2()</code></td>
<td>Escribir <code>csv</code> (coma decimal)</td>
</tr>
<tr class="odd">
<td><code>write_tsv()</code></td>
<td>Escribir delimitado por tabulador</td>
</tr>
<tr class="even">
<td><code>write_delim()</code></td>
<td>Escribir con delimitador personalizado</td>
</tr>
<tr class="odd">
<td><code>write_rds()</code></td>
<td>Guardar objeto R en <code>.rds</code></td>
</tr>
</tbody>
</table>
</p>
</div>
<div class="admon-box observacion">
<div class="admon-title">
<span class="icon"></span> Argumentos comunes (lectura)
</div>
<p>
<table>
<colgroup>
<col width="13%" />
<col width="58%" />
<col width="27%" />
</colgroup>
<thead>
<tr class="header">
<th>Argumento</th>
<th>Qué controla</th>
<th>Ejemplo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>col_types</code></td>
<td>Tipos de columnas (explícitos)</td>
<td><code>col_types = cols(id = col_integer())</code></td>
</tr>
<tr class="even">
<td><code>na</code></td>
<td>Cadenas que se tratarán como NA</td>
<td><code>na = c("", "NA", "NULL")</code></td>
</tr>
<tr class="odd">
<td><code>locale</code></td>
<td>Configuración regional (decimal, fecha, tz, encoding)</td>
<td><code>locale(decimal_mark = ",")</code></td>
</tr>
<tr class="even">
<td><code>skip</code> / <code>n_max</code></td>
<td>Filas a omitir / máximo de filas a leer</td>
<td><code>skip = 2, n_max = 1e5</code></td>
</tr>
<tr class="odd">
<td><code>comment</code></td>
<td>Prefijo de comentario para ignorar líneas</td>
<td><code>comment = "#"</code></td>
</tr>
<tr class="even">
<td><code>guess_max</code></td>
<td>Filas usadas para “adivinar” tipos</td>
<td><code>guess_max = 100000</code></td>
</tr>
<tr class="odd">
<td><code>show_col_types</code></td>
<td>Muestra la conjetura de tipos al leer</td>
<td><code>show_col_types = FALSE</code></td>
</tr>
</tbody>
</table>
<blockquote>
<p><strong>Tip</strong>: cuando los tipos son críticos, <strong>no confíes solo en la inferencia</strong>: pasa <code>col_types</code> explícito.</p>
</blockquote>
</p>
</div>
<ul>
<li>Veamos el siguiente ejemplo. Carguemos los siguientes datos:</li>
</ul>
<details class=chunk-details open><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="etltidyverse.html#cb14-1" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb14-2"><a href="etltidyverse.html#cb14-2" tabindex="-1"></a></span>
<span id="cb14-3"><a href="etltidyverse.html#cb14-3" tabindex="-1"></a><span class="co"># CSV con punto decimal y encabezados</span></span>
<span id="cb14-4"><a href="etltidyverse.html#cb14-4" tabindex="-1"></a>dfReadr <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;data/StudyArea.csv&quot;</span>,           </span>
<span id="cb14-5"><a href="etltidyverse.html#cb14-5" tabindex="-1"></a>  <span class="at">col_types =</span> <span class="fu">cols</span>(<span class="at">.default =</span> <span class="st">&quot;c&quot;</span>),  <span class="co"># Columnas (.default) como &quot;character&quot;</span></span>
<span id="cb14-6"><a href="etltidyverse.html#cb14-6" tabindex="-1"></a>  <span class="at">col_names =</span> <span class="cn">TRUE</span>)                  <span class="co"># la 1ra fila como nombres de las columnas</span></span>
<span id="cb14-7"><a href="etltidyverse.html#cb14-7" tabindex="-1"></a></span>
<span id="cb14-8"><a href="etltidyverse.html#cb14-8" tabindex="-1"></a><span class="fu">head</span>(dfReadr)</span></code></pre></div>
</details>
<pre><code>## # A tibble: 6 × 14
##   FID   ORGANIZATI UNIT  SUBUNIT SUBUNIT2        FIRENAME CAUSE YEAR_ STARTDATED
##   &lt;chr&gt; &lt;chr&gt;      &lt;chr&gt; &lt;chr&gt;   &lt;chr&gt;           &lt;chr&gt;    &lt;chr&gt; &lt;chr&gt; &lt;chr&gt;     
## 1 0     FWS        81682 USCADBR San Diego Bay … PUMP HO… Human 2001  1/1/01 0:…
## 2 1     FWS        81682 USCADBR San Diego Bay … I5       Human 2002  5/3/02 0:…
## 3 2     FWS        81682 USCADBR San Diego Bay … SOUTHBAY Human 2002  6/1/02 0:…
## 4 3     FWS        81682 USCADBR San Diego Bay … MARINA   Human 2001  7/12/01 0…
## 5 4     FWS        81682 USCADBR San Diego Bay … HILL     Human 1994  9/13/94 0…
## 6 5     FWS        81682 USCADBR San Diego Bay … IRRIGAT… Human 1994  4/22/94 0…
## # ℹ 5 more variables: CONTRDATED &lt;chr&gt;, OUTDATED &lt;chr&gt;, STATE &lt;chr&gt;,
## #   STATE_FIPS &lt;chr&gt;, TOTALACRES &lt;chr&gt;</code></pre>
<details class=chunk-details open><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="etltidyverse.html#cb16-1" tabindex="-1"></a><span class="fu">spec</span>(dfReadr)         <span class="co"># Esquema de tipos</span></span></code></pre></div>
</details>
<pre><code>## cols(
##   .default = col_character(),
##   FID = col_character(),
##   ORGANIZATI = col_character(),
##   UNIT = col_character(),
##   SUBUNIT = col_character(),
##   SUBUNIT2 = col_character(),
##   FIRENAME = col_character(),
##   CAUSE = col_character(),
##   YEAR_ = col_character(),
##   STARTDATED = col_character(),
##   CONTRDATED = col_character(),
##   OUTDATED = col_character(),
##   STATE = col_character(),
##   STATE_FIPS = col_character(),
##   TOTALACRES = col_character()
## )</code></pre>
<ul>
<li><p>Al ejecutar nuevamente la función sin el argumento <code>col_types</code>, <strong>R</strong>* intentará detectar automáticamente el tipo de dato de cada columna. En este proceso se mostrará primero un listado con los nombres de las columnas y el tipo asignado a cada una, seguido de un mensaje de advertencia que indica la presencia de errores de análisis durante la importación, lo cual ejemplifica las inconsistencias que pueden surgir al dejar la inferencia de tipos en manos del sistema.</p></li>
<li><p>Actualice el código como se muestra a continuación y ejecútelo nuevamente. En este caso, se especifica que la columna <code>UNIT</code> debe ser importada como un dato de tipo carácter (texto):</p></li>
</ul>
<details class=chunk-details open><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="etltidyverse.html#cb18-1" tabindex="-1"></a>dfReadr <span class="ot">=</span> <span class="fu">read_csv</span>(<span class="st">&quot;data/StudyArea.csv&quot;</span>, </span>
<span id="cb18-2"><a href="etltidyverse.html#cb18-2" tabindex="-1"></a>                   <span class="at">col_types =</span> <span class="fu">list</span>(<span class="at">FID =</span> <span class="fu">col_character</span>()),</span>
<span id="cb18-3"><a href="etltidyverse.html#cb18-3" tabindex="-1"></a>                   <span class="at">col_names =</span> <span class="cn">TRUE</span>)                </span>
<span id="cb18-4"><a href="etltidyverse.html#cb18-4" tabindex="-1"></a></span>
<span id="cb18-5"><a href="etltidyverse.html#cb18-5" tabindex="-1"></a><span class="fu">head</span>(dfReadr)</span></code></pre></div>
</details>
<pre><code>## # A tibble: 6 × 14
##   FID   ORGANIZATI UNIT  SUBUNIT SUBUNIT2        FIRENAME CAUSE YEAR_ STARTDATED
##   &lt;chr&gt; &lt;chr&gt;      &lt;chr&gt; &lt;chr&gt;   &lt;chr&gt;           &lt;chr&gt;    &lt;chr&gt; &lt;dbl&gt; &lt;chr&gt;     
## 1 0     FWS        81682 USCADBR San Diego Bay … PUMP HO… Human  2001 1/1/01 0:…
## 2 1     FWS        81682 USCADBR San Diego Bay … I5       Human  2002 5/3/02 0:…
## 3 2     FWS        81682 USCADBR San Diego Bay … SOUTHBAY Human  2002 6/1/02 0:…
## 4 3     FWS        81682 USCADBR San Diego Bay … MARINA   Human  2001 7/12/01 0…
## 5 4     FWS        81682 USCADBR San Diego Bay … HILL     Human  1994 9/13/94 0…
## 6 5     FWS        81682 USCADBR San Diego Bay … IRRIGAT… Human  1994 4/22/94 0…
## # ℹ 5 more variables: CONTRDATED &lt;chr&gt;, OUTDATED &lt;chr&gt;, STATE &lt;chr&gt;,
## #   STATE_FIPS &lt;dbl&gt;, TOTALACRES &lt;dbl&gt;</code></pre>
</div>
</div>
<div id="transformación-de-datos" class="section level2 hasAnchor" number="2.3">
<h2><span class="header-section-number">2.3</span> Transformación de datos<a href="#transformaci%C3%B3n-de-datos" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ul>
<li><p>Antes de realizar un análisis de datos en <strong>R</strong>, con frecuencia es necesario manipular o transformar la información de distintas formas.<br />
Para ello, el paquete <strong>dplyr</strong>, que hace parte del ecosistema <strong>tidyverse</strong>, ofrece un conjunto de funciones que facilitan la transformación y manejo de datos de manera eficiente y estructurada.</p></li>
<li><p>En esta sección abordaremos los siguientes aspectos fundamentales:</p>
<ul>
<li>Filtrar registros para obtener subconjuntos de datos<br />
</li>
<li>Seleccionar y limitar columnas específicas<br />
</li>
<li>Ordenar filas en forma ascendente o descendente<br />
</li>
<li>Incorporar nuevas filas a un conjunto existente<br />
</li>
<li>Resumir y agrupar información<br />
</li>
<li>Utilizar canalización (<em>pipes</em>) para mejorar la legibilidad y eficiencia del código</li>
</ul></li>
</ul>
<div id="el-paquete-dplyr" class="section level3 hasAnchor" number="2.3.1">
<h3><span class="header-section-number">2.3.1</span> El paquete <code>dplyr</code><a href="etltidyverse.html#el-paquete-dplyr" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="admon-box definicion">
<div class="admon-title">
<span class="icon"></span> Definición
</div>
<p>
El paquete <strong>dplyr</strong> fue desarrollado por <em>Hadley Wickham</em> de RStudio y es una versión optimizada y destilada de su paquete <strong>plyr</strong>.
</p>
</div>
<ul>
<li>Una importante contribución de <code>dplyr</code> es que proporciona una <strong>gramática</strong> (en particular, <em>verbos</em>) para la <em>manipulación de datos y operación con data frames</em>.<br />
</li>
<li>Con esta gramática se puede comunicar de forma comprensible lo que se está haciendo a un data frame, lo cual es muy útil porque proporciona una abstracción para la manipulación de datos que antes no existía.<br />
</li>
<li>Otra ventaja es que las funciones de <code>dplyr</code> son muy rápidas, ya que muchas operaciones clave están codificadas en <code>C++</code>.</li>
</ul>
</div>
<div id="operador" class="section level3 hasAnchor" number="2.3.2">
<h3><span class="header-section-number">2.3.2</span> Operador <code>%&gt;%</code><a href="etltidyverse.html#operador" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li>El operador <strong>pipeline</strong> <code>%&gt;%</code> resulta muy útil para <strong>encadenar múltiples funciones de <code>dplyr</code> en una secuencia de operaciones</strong>. Antes de usarlo, cuando se necesitaba aplicar varias funciones de manera consecutiva, la expresión debía escribirse como una <strong>secuencia de funciones anidadas</strong>, lo cual resulta poco legible. Por ejemplo:</li>
</ul>
<details class=chunk-details open><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="etltidyverse.html#cb20-1" tabindex="-1"></a><span class="fu">third</span>(<span class="fu">second</span>(<span class="fu">first</span>(x)))</span></code></pre></div>
</details>
<ul>
<li>Este estilo de anidamiento <strong>no refleja la manera natural de pensar en una secuencia de pasos</strong>. En cambio, el operador <code>%&gt;%</code> permite expresar la secuencia <strong>de izquierda a derecha</strong>, facilitando la lectura y comprensión del código.</li>
</ul>
<details class=chunk-details open><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="etltidyverse.html#cb21-1" tabindex="-1"></a><span class="fu">first</span>(x) <span class="sc">%&gt;%</span></span>
<span id="cb21-2"><a href="etltidyverse.html#cb21-2" tabindex="-1"></a>  second <span class="sc">%&gt;%</span></span>
<span id="cb21-3"><a href="etltidyverse.html#cb21-3" tabindex="-1"></a>  third</span></code></pre></div>
</details>
</div>
<div id="filtrar-datos-para-crear-un-subconjunto" class="section level3 hasAnchor" number="2.3.3">
<h3><span class="header-section-number">2.3.3</span> Filtrar datos para crear un subconjunto<a href="etltidyverse.html#filtrar-datos-para-crear-un-subconjunto" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="admon-box definicion">
<div class="admon-title">
<span class="icon"></span> Definición: <code>filter()</code>
</div>
<p>
<p>La función <code>filter()</code> del paquete <strong>dplyr</strong> se utiliza para
<em>extraer subconjuntos de filas de un <code>dataframe</code></em> en función de una o más condiciones lógicas. Es similar a la función <code>subset()</code> de R base, pero resulta más rápida y eficiente.</p>
El primer argumento que recibe <code>filter()</code> siempre es un objeto de tipo <code>dataframe</code>, mientras que
los argumentos adicionales corresponden a las expresiones condicionales que definen el filtrado.
</p>
</div>
<div class="admon-box ejemplo">
<div class="admon-title">
<span class="icon"></span> Ejemplo de incendios forestales
</div>
<p>
<p>El repositorio <strong><a href="https://github.com/cdeoroaguado/Datos/blob/main/datarstudio/RDataSets.zip">RDataSets</a></strong> contiene el archivo <code>StudyArea.csv</code>, un archivo separado por comas con información de incendios forestales ocurridos entre los años <strong>1980 y 2016</strong> en los estados de <strong>California, Oregón, Washington, Idaho, Montana, Wyoming, Colorado, Utah, Nevada, Arizona y Nuevo México</strong>.</p>
<p>Este archivo cuenta con <strong>aproximadamente 439.000 registros</strong> y <strong>37 columnas</strong> que describen las características de cada incendio durante este periodo.</p>
En este <code>dataframe</code> de incendios forestales tiene una columna llamada <strong>TOTALACRES</strong>, la cual registra el número de acres quemados por evento.
</p>
<details class=chunk-details open><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="etltidyverse.html#cb22-1" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;data/StudyArea.csv&quot;</span>)</span>
<span id="cb22-2"><a href="etltidyverse.html#cb22-2" tabindex="-1"></a></span>
<span id="cb22-3"><a href="etltidyverse.html#cb22-3" tabindex="-1"></a><span class="fu">head</span>(df,<span class="at">n=</span><span class="dv">3</span>)</span></code></pre></div>
</details>
<pre><code>##   FID ORGANIZATI  UNIT SUBUNIT                               SUBUNIT2
## 1   0        FWS 81682 USCADBR San Diego Bay National Wildlife Refuge
## 2   1        FWS 81682 USCADBR San Diego Bay National Wildlife Refuge
## 3   2        FWS 81682 USCADBR San Diego Bay National Wildlife Refuge
##     FIRENAME CAUSE YEAR_  STARTDATED  CONTRDATED OUTDATED      STATE STATE_FIPS
## 1 PUMP HOUSE Human  2001 1/1/01 0:00 1/1/01 0:00          California          6
## 2         I5 Human  2002 5/3/02 0:00 5/3/02 0:00          California          6
## 3   SOUTHBAY Human  2002 6/1/02 0:00 6/1/02 0:00          California          6
##   TOTALACRES
## 1        0.1
## 2        3.0
## 3        0.5</code></pre>
</div>
<p style="text-align: center;">
<strong>Solución</strong>
</p>
<ul>
<li>Crear un subconjunto de registros que contenga sólo los incendios forestales de más de <span class="math inline">\(25000\)</span> acres.</li>
</ul>
<details class=chunk-details open><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="etltidyverse.html#cb24-1" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb24-2"><a href="etltidyverse.html#cb24-2" tabindex="-1"></a></span>
<span id="cb24-3"><a href="etltidyverse.html#cb24-3" tabindex="-1"></a>df <span class="sc">%&gt;%</span> </span>
<span id="cb24-4"><a href="etltidyverse.html#cb24-4" tabindex="-1"></a>  <span class="fu">filter</span>(TOTALACRES <span class="sc">&gt;=</span> <span class="dv">25000</span>)</span></code></pre></div>
</details>
<ul>
<li>Crear un subconjunto de registros que contenga sólo los incendios forestales de más de <span class="math inline">\(1000\)</span> acres en el año <span class="math inline">\(2016\)</span>.</li>
</ul>
<details class=chunk-details open><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="etltidyverse.html#cb25-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span> </span>
<span id="cb25-2"><a href="etltidyverse.html#cb25-2" tabindex="-1"></a>  <span class="fu">filter</span>(TOTALACRES <span class="sc">&gt;=</span> <span class="dv">1000</span>,YEAR_<span class="sc">==</span> <span class="dv">2016</span>)</span></code></pre></div>
</details>
<ul>
<li>Crear un subconjunto de registros que contenga sólo los incendios forestales de más de <span class="math inline">\(1000\)</span> acres en el año <span class="math inline">\(2016\)</span>, pero usa el operador <code>&amp;</code>.</li>
</ul>
<details class=chunk-details open><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="etltidyverse.html#cb26-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span> </span>
<span id="cb26-2"><a href="etltidyverse.html#cb26-2" tabindex="-1"></a>  <span class="fu">filter</span>(TOTALACRES <span class="sc">&gt;=</span> <span class="dv">1000</span> <span class="sc">&amp;</span> YEAR_<span class="sc">==</span> <span class="dv">2016</span>)</span></code></pre></div>
</details>
<ul>
<li>Crear un subconjunto de registros que contenga sólo los años <span class="math inline">\(2010\)</span>, <span class="math inline">\(2011\)</span> y <span class="math inline">\(2012\)</span></li>
</ul>
<details class=chunk-details open><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="etltidyverse.html#cb27-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span> </span>
<span id="cb27-2"><a href="etltidyverse.html#cb27-2" tabindex="-1"></a>  <span class="fu">filter</span>(YEAR_ <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">2010</span>, <span class="dv">2011</span>, <span class="dv">2012</span>))</span></code></pre></div>
</details>
</div>
<div id="acotar-la-lista-de-columnas-con-select" class="section level3 hasAnchor" number="2.3.4">
<h3><span class="header-section-number">2.3.4</span> Acotar la lista de columnas con <code>select()</code><a href="etltidyverse.html#acotar-la-lista-de-columnas-con-select" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="admon-box definicion">
<div class="admon-title">
<span class="icon"></span> Definición: <code>select()</code>
</div>
<p>
La función <code>select()</code> del paquete <strong>dplyr</strong> se emplea para
<em>elegir columnas específicas de un dataframe</em>.<br />
Es especialmente útil cuando se trabaja con conjuntos de datos extensos y solo se requiere un subconjunto de variables.
</p>
</div>
<p>Continuando con el ejemplo de las incendios forestales</p>
<ul>
<li>Selecciona las columnas <code>FIRENAME</code>, <code>TOTALACRES</code>, <code>YEAR_</code></li>
</ul>
<details class=chunk-details open><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="etltidyverse.html#cb28-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span> </span>
<span id="cb28-2"><a href="etltidyverse.html#cb28-2" tabindex="-1"></a>  <span class="fu">select</span>(FIRENAME, TOTALACRES, YEAR_)</span></code></pre></div>
</details>
<ul>
<li>Selecciona las columnas <code>FIRENAME</code>, <code>TOTALACRES</code>, <code>YEAR_</code>, cambian el nombre de <code>TOTALACRES</code> por <code>ACRES</code> y <code>YEAR_</code> por <code>YR</code>.</li>
</ul>
<details class=chunk-details open><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="etltidyverse.html#cb29-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span> </span>
<span id="cb29-2"><a href="etltidyverse.html#cb29-2" tabindex="-1"></a>  <span class="fu">select</span>(<span class="st">&quot;FIRE&quot;</span> <span class="ot">=</span> <span class="st">&quot;FIRENAME&quot;</span>, <span class="st">&quot;ACRES&quot;</span> <span class="ot">=</span><span class="st">&quot;TOTALACRES&quot;</span>, <span class="st">&quot;YR&quot;</span> <span class="ot">=</span> <span class="st">&quot;YEAR_&quot;</span>)</span></code></pre></div>
</details>
<ul>
<li>Selecciona las columnas que contengan la palabra <code>DATE</code></li>
</ul>
<details class=chunk-details open><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="etltidyverse.html#cb30-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span> </span>
<span id="cb30-2"><a href="etltidyverse.html#cb30-2" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">contains</span>(<span class="st">&quot;DATE&quot;</span>))</span></code></pre></div>
</details>
<ul>
<li>Selecciona las columnas que contengan la palabra <code>DATE</code> y también inicien con <code>TOTAL</code></li>
</ul>
<details class=chunk-details open><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="etltidyverse.html#cb31-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span> </span>
<span id="cb31-2"><a href="etltidyverse.html#cb31-2" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">contains</span>(<span class="st">&quot;DATE&quot;</span>),<span class="fu">starts_with</span>(<span class="st">&quot;TOTAL&quot;</span>))</span></code></pre></div>
</details>
<div class="admon-box nota">
<div class="admon-title">
<span class="icon"></span> Funciones de ayuda para <code>select()</code>
</div>
<p>
La función <code>select()</code> puede complementarse con una serie de <strong>funciones auxiliares</strong> que permiten
filtrar las columnas de manera más flexible y eficiente. Estas funciones son especialmente útiles cuando se trabaja con
conjuntos de datos amplios o cuando los nombres de las variables siguen un patrón específico.
</p>
<ul>
<li>
<code>starts_with(“texto”)</code>: selecciona las columnas cuyos nombres comienzan con el texto indicado.
</li>
<li>
<code>ends_with(“texto”)</code>: selecciona las columnas cuyos nombres terminan con el texto indicado.
</li>
<li>
<code>contains(“texto”)</code>: selecciona las columnas cuyos nombres contienen el texto indicado.
</li>
<li>
<code>matches(“regex”)</code>: selecciona las columnas cuyos nombres cumplen con una expresión regular.
</li>
<li>
<code>num_range(“x”, 1:5)</code>: selecciona un rango de columnas numeradas (ejemplo: <code>x1</code>, <code>x2</code>, …, <code>x5</code>).
</li>
</ul>
</div>
</div>
<div id="organizar-las-filas" class="section level3 hasAnchor" number="2.3.5">
<h3><span class="header-section-number">2.3.5</span> Organizar las filas<a href="etltidyverse.html#organizar-las-filas" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="admon-box definicion">
<div class="admon-title">
<span class="icon"></span> Definición: <code>arrange()</code>
</div>
<p>
La función <code>arrange()</code> del paquete <strong>dplyr</strong> se utiliza para
<em>ordenar las filas de un dataframe</em> en función de una o varias columnas.<br />
De manera predeterminada, organiza en <strong>orden ascendente</strong>, aunque puede invertirse a
<strong>orden descendente</strong> con la función <code>desc()</code>.
</p>
</div>
<p>Continuando con el ejemplo de los incendios forestales</p>
<ul>
<li>Filtrar el conjunto de datos para que contenga solo los incendios de más de 1.000 acres quemados del año 2016. Despues selecciona las columnas <code>FIRENAME</code>, <code>TOTALACRES</code>, <code>YEAR_</code> y renombralas <code>NAME</code>, <code>ACRES</code>, <code>YR</code>, respectivamente. Finalmente, ordena <code>ACRES</code> de forma ascendente y muestrame las 5 ultimas.</li>
</ul>
<details class=chunk-details open><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="etltidyverse.html#cb32-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span> </span>
<span id="cb32-2"><a href="etltidyverse.html#cb32-2" tabindex="-1"></a>  <span class="fu">filter</span>(TOTALACRES <span class="sc">&gt;=</span> <span class="dv">1000</span>, YEAR_ <span class="sc">==</span> <span class="dv">2016</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb32-3"><a href="etltidyverse.html#cb32-3" tabindex="-1"></a>  <span class="fu">select</span>(<span class="st">&quot;NAME&quot;</span> <span class="ot">=</span> <span class="st">&quot;FIRENAME&quot;</span>, <span class="st">&quot;ACRES&quot;</span> <span class="ot">=</span> <span class="st">&quot;TOTALACRES&quot;</span>, <span class="st">&quot;YR&quot;</span> <span class="ot">=</span> <span class="st">&quot;YEAR_&quot;</span>) <span class="sc">%&gt;%</span>   <span class="fu">arrange</span>(ACRES) <span class="sc">%&gt;%</span> </span>
<span id="cb32-4"><a href="etltidyverse.html#cb32-4" tabindex="-1"></a>  <span class="fu">tail</span>(<span class="at">n=</span><span class="dv">5</span>)</span></code></pre></div>
</details>
<pre><code>##         NAME  ACRES   YR
## 148    Cedar  45977 2016
## 149  Erskine  48007 2016
## 150 Range 12 171915 2016
## 151  Junkins 181320 2016
## 152  PIONEER 188404 2016</code></pre>
<ul>
<li>Filtrar el conjunto de datos para que contenga solo los incendios de más de 2.000 acres quemados del año 2016. Despues selecciona las columnas <code>FIRENAME</code>, <code>TOTALACRES</code>, <code>YEAR_</code> y renombralas <code>NAME</code>, <code>ACRES</code>, <code>YR</code>, respectivamente. Finalmente, ordena <code>ACRES</code> de forma descendente y muestrame las 5 primeras.</li>
</ul>
<details class=chunk-details open><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="etltidyverse.html#cb34-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span> </span>
<span id="cb34-2"><a href="etltidyverse.html#cb34-2" tabindex="-1"></a>  <span class="fu">filter</span>(TOTALACRES <span class="sc">&gt;=</span> <span class="dv">2000</span>, YEAR_ <span class="sc">==</span> <span class="dv">2016</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb34-3"><a href="etltidyverse.html#cb34-3" tabindex="-1"></a>  <span class="fu">select</span>(<span class="st">&quot;NAME&quot;</span> <span class="ot">=</span> <span class="st">&quot;FIRENAME&quot;</span>, <span class="st">&quot;ACRES&quot;</span> <span class="ot">=</span> <span class="st">&quot;TOTALACRES&quot;</span>, <span class="st">&quot;YR&quot;</span> <span class="ot">=</span> <span class="st">&quot;YEAR_&quot;</span>) <span class="sc">%&gt;%</span>   <span class="fu">arrange</span>(<span class="fu">desc</span>(ACRES)) <span class="sc">%&gt;%</span> </span>
<span id="cb34-4"><a href="etltidyverse.html#cb34-4" tabindex="-1"></a>  <span class="fu">head</span>(<span class="at">n=</span><span class="dv">5</span>)</span></code></pre></div>
</details>
<pre><code>##       NAME  ACRES   YR
## 1  PIONEER 188404 2016
## 2  Junkins 181320 2016
## 3 Range 12 171915 2016
## 4  Erskine  48007 2016
## 5    Cedar  45977 2016</code></pre>
</div>
<div id="añadir-columnas-con-mutate" class="section level3 hasAnchor" number="2.3.6">
<h3><span class="header-section-number">2.3.6</span> Añadir columnas con <code>mutate</code><a href="#a%C3%B1adir-columnas-con-mutate" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="admon-box definicion">
<div class="admon-title">
<span class="icon"></span> Definición: <code>mutate()</code>
</div>
<p>
La función <code>mutate()</code> del paquete <strong>dplyr</strong> se utiliza para
<em>crear nuevas variables o transformar las existentes</em> dentro de un <code>dataframe</code>.<br />
Es especialmente útil cuando se desea generar columnas derivadas a partir de operaciones aritméticas,
funciones estadísticas o transformaciones sobre variables ya presentes en los datos.<br />
Gracias a su sintaxis sencilla y legible, <code>mutate()</code> ofrece una forma clara y estructurada
de enriquecer un conjunto de datos sin necesidad de sobrescribir la información original.
</p>
</div>
<p>Continuando con el ejemplo de los incendios forestales</p>
<ul>
<li>Seleccione únicamente las columnas <strong>ORGANIZATI</strong>, <strong>STATE</strong>, <strong>YEAR_</strong>, <strong>TOTALACRES</strong>, <strong>CAUSE</strong> y <strong>STARTDATED</strong>, filtre los registros para que solo se incluyan los incendios con más de <strong>1.000 acres</strong> quemados y cuya causa sea <strong>Humana</strong> o <strong>Natural</strong>, cree una nueva columna llamada <strong>DOY</strong> que indique el día del año en que inició cada incendio a partir de la columna <strong>STARTDATED</strong>, y finalmente muestre las primeras filas del resultado.</li>
</ul>
<p>Carguemos nuevamente los datos</p>
<details class=chunk-details open><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="etltidyverse.html#cb36-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb36-2"><a href="etltidyverse.html#cb36-2" tabindex="-1"></a>  <span class="fu">select</span>(ORGANIZATI, STATE, YEAR_, TOTALACRES, CAUSE, STARTDATED) <span class="sc">%&gt;%</span></span>
<span id="cb36-3"><a href="etltidyverse.html#cb36-3" tabindex="-1"></a>  <span class="fu">filter</span>(TOTALACRES <span class="sc">&gt;=</span> <span class="dv">1000</span> <span class="sc">&amp;</span> CAUSE <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">&quot;Human&quot;</span>, <span class="st">&quot;Natural&quot;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb36-4"><a href="etltidyverse.html#cb36-4" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">DOY =</span> <span class="fu">yday</span>(<span class="fu">as.Date</span>(STARTDATED, <span class="at">format=</span><span class="st">&quot;%m/%d/%y%H:%M&quot;</span>))) <span class="ot">-&gt;</span> df_sol</span>
<span id="cb36-5"><a href="etltidyverse.html#cb36-5" tabindex="-1"></a></span>
<span id="cb36-6"><a href="etltidyverse.html#cb36-6" tabindex="-1"></a><span class="co"># Vista rápida</span></span>
<span id="cb36-7"><a href="etltidyverse.html#cb36-7" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">head</span>(df_sol))</span></code></pre></div>
</details>
<table>
<thead>
<tr class="header">
<th align="left">ORGANIZATI</th>
<th align="left">STATE</th>
<th align="right">YEAR_</th>
<th align="right">TOTALACRES</th>
<th align="left">CAUSE</th>
<th align="left">STARTDATED</th>
<th align="right">DOY</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">FWS</td>
<td align="left">Arizona</td>
<td align="right">1988</td>
<td align="right">1500</td>
<td align="left">Human</td>
<td align="left">3/26/88 0:00</td>
<td align="right">86</td>
</tr>
<tr class="even">
<td align="left">FWS</td>
<td align="left">Arizona</td>
<td align="right">1986</td>
<td align="right">10390</td>
<td align="left">Human</td>
<td align="left">5/15/86 0:00</td>
<td align="right">135</td>
</tr>
<tr class="odd">
<td align="left">FWS</td>
<td align="left">Montana</td>
<td align="right">1986</td>
<td align="right">1400</td>
<td align="left">Human</td>
<td align="left">6/27/86 0:00</td>
<td align="right">178</td>
</tr>
<tr class="even">
<td align="left">FWS</td>
<td align="left">Arizona</td>
<td align="right">2002</td>
<td align="right">1035</td>
<td align="left">Human</td>
<td align="left">2/28/02 0:00</td>
<td align="right">59</td>
</tr>
<tr class="odd">
<td align="left">FWS</td>
<td align="left">Arizona</td>
<td align="right">2000</td>
<td align="right">5700</td>
<td align="left">Human</td>
<td align="left">4/9/00 0:00</td>
<td align="right">100</td>
</tr>
<tr class="even">
<td align="left">FWS</td>
<td align="left">Arizona</td>
<td align="right">2000</td>
<td align="right">2750</td>
<td align="left">Human</td>
<td align="left">5/14/00 0:00</td>
<td align="right">135</td>
</tr>
</tbody>
</table>
<div class="admon-box observacion">
<div class="admon-title">
<span class="icon"></span> Observación sobre <code>lubridate</code>
</div>
<p>
El paquete <strong>lubridate</strong> del ecosistema <em>tidyverse</em> está diseñado para
simplificar la manipulación de fechas y tiempos en R.<br />
Proporciona funciones intuitivas como <code>ymd()</code>, <code>mdy()</code> o <code>dmy()</code>
para convertir cadenas en objetos de tipo fecha, así como <code>ymd_hms()</code> o <code>mdy_hm()</code>
para manejar fechas con hora, minutos y segundos.<br />
Además, incluye utilidades como <code>yday()</code> (día del año), <code>wday()</code> (día de la semana),
<code>month()</code> o <code>year()</code>, que permiten extraer y operar sobre componentes específicos de una fecha
de manera clara y eficiente.<br />
En comparación con las funciones base de R, <code>lubridate</code> ofrece una sintaxis más legible y reduce errores
asociados al manejo de distintos formatos de fecha y hora.
</p>
<table style="width:100%;">
<colgroup>
<col width="14%" />
<col width="56%" />
<col width="29%" />
</colgroup>
<thead>
<tr class="header">
<th>Función</th>
<th>Descripción</th>
<th>Ejemplo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>ymd()</code></td>
<td>Convierte cadenas con formato Año-Mes-Día a fecha (<code>YYYY-MM-DD</code>).</td>
<td><code>ymd("2023-08-21")</code> → <code>2023-08-21</code></td>
</tr>
<tr class="even">
<td><code>mdy()</code></td>
<td>Convierte cadenas con formato Mes-Día-Año a fecha (<code>MM-DD-YYYY</code>).</td>
<td><code>mdy("08-21-2023")</code> → <code>2023-08-21</code></td>
</tr>
<tr class="odd">
<td><code>dmy()</code></td>
<td>Convierte cadenas con formato Día-Mes-Año a fecha (<code>DD-MM-YYYY</code>).</td>
<td><code>dmy("21-08-2023")</code> → <code>2023-08-21</code></td>
</tr>
<tr class="even">
<td><code>ymd_hms()</code></td>
<td>Convierte a fecha con hora, minutos y segundos.</td>
<td><code>ymd_hms("2023-08-21 14:30:15")</code></td>
</tr>
<tr class="odd">
<td><code>mdy_hm()</code></td>
<td>Convierte a fecha con hora y minutos.</td>
<td><code>mdy_hm("08-21-2023 14:30")</code></td>
</tr>
<tr class="even">
<td><code>year()</code></td>
<td>Extrae el año de una fecha.</td>
<td><code>year(ymd("2023-08-21"))</code> → <code>2023</code></td>
</tr>
<tr class="odd">
<td><code>month()</code></td>
<td>Extrae el mes de una fecha (numérico o etiqueta si <code>label=TRUE</code>).</td>
<td><code>month(ymd("2023-08-21"), label=TRUE)</code> → <code>Aug</code></td>
</tr>
<tr class="even">
<td><code>day()</code></td>
<td>Extrae el día del mes.</td>
<td><code>day(ymd("2023-08-21"))</code> → <code>21</code></td>
</tr>
<tr class="odd">
<td><code>yday()</code></td>
<td>Devuelve el día del año (1–365/366).</td>
<td><code>yday(ymd("2023-08-21"))</code> → <code>233</code></td>
</tr>
<tr class="even">
<td><code>wday()</code></td>
<td>Devuelve el día de la semana (numérico o etiqueta si <code>label=TRUE</code>).</td>
<td><code>wday(ymd("2023-08-21"), label=TRUE)</code> → <code>Mon</code></td>
</tr>
<tr class="odd">
<td><code>hour()</code>, <code>minute()</code>, <code>second()</code></td>
<td>Extraen hora, minutos o segundos de un objeto fecha-hora.</td>
<td><code>hour(ymd_hms("2023-08-21 14:30:15"))</code> → <code>14</code></td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="agrupación-y-resumen-de-los-datos" class="section level3 hasAnchor" number="2.3.7">
<h3><span class="header-section-number">2.3.7</span> Agrupación y resumen de los datos<a href="#agrupaci%C3%B3n-y-resumen-de-los-datos" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="admon-box definicion">
<div class="admon-title">
<span class="icon"></span> Definición: <code>group_by()</code>
</div>
<p>
La función <code>group_by()</code> del paquete <strong>dplyr</strong> se utiliza para
<em>agrupar un dataframe en función de una o varias variables</em>.<br />
Este agrupamiento no modifica los datos en sí, sino que establece una estructura que permite
aplicar funciones de resumen o transformación sobre cada grupo de manera independiente.<br />
Generalmente, <code>group_by()</code> se usa en combinación con <code>summarise()</code>,
<code>mutate()</code> u otras funciones de <code>dplyr</code>.
</p>
</div>
<p>Continuando con el ejemplo de incendios forestales</p>
<ul>
<li>Seleccione únicamente las columnas <strong>ORGANIZATI</strong>, <strong>STATE</strong>, <strong>YEAR_</strong>, <strong>TOTALACRES</strong> y <strong>CAUSE</strong> , filtre los registros para que solo se incluyan los incendios con más de <strong>1.000 acres</strong> quemados, cree una nueva columna llamada <strong>DECADE</strong> que define la década en la que se produjo cada incendio, agrupa por<strong>DECADE</strong> y finalmente un resumen numérico completo del tamaño de los incendios forestales por década.</li>
</ul>
<details class=chunk-details open><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="etltidyverse.html#cb37-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb37-2"><a href="etltidyverse.html#cb37-2" tabindex="-1"></a>  <span class="fu">select</span>(ORGANIZATI, STATE, YEAR_, TOTALACRES, CAUSE) <span class="sc">%&gt;%</span></span>
<span id="cb37-3"><a href="etltidyverse.html#cb37-3" tabindex="-1"></a>  <span class="fu">filter</span>(TOTALACRES <span class="sc">&gt;=</span> <span class="dv">1000</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb37-4"><a href="etltidyverse.html#cb37-4" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">DECADE =</span> <span class="fu">ifelse</span>(YEAR_ <span class="sc">%in%</span> <span class="dv">1980</span><span class="sc">:</span><span class="dv">1989</span>, <span class="st">&quot;1980-1989&quot;</span>, </span>
<span id="cb37-5"><a href="etltidyverse.html#cb37-5" tabindex="-1"></a>                          <span class="fu">ifelse</span>(YEAR_ <span class="sc">%in%</span> <span class="dv">1990</span><span class="sc">:</span><span class="dv">1999</span>, <span class="st">&quot;1990-1999&quot;</span>,</span>
<span id="cb37-6"><a href="etltidyverse.html#cb37-6" tabindex="-1"></a>                          <span class="fu">ifelse</span>(YEAR_ <span class="sc">%in%</span> <span class="dv">2000</span><span class="sc">:</span><span class="dv">2009</span>, <span class="st">&quot;2000-2009&quot;</span>, </span>
<span id="cb37-7"><a href="etltidyverse.html#cb37-7" tabindex="-1"></a>                          <span class="fu">ifelse</span>(YEAR_ <span class="sc">%in%</span> <span class="dv">2010</span><span class="sc">:</span><span class="dv">2016</span>, <span class="st">&quot;2010-2016&quot;</span>, <span class="st">&quot;-99&quot;</span>))))) <span class="sc">%&gt;%</span> </span>
<span id="cb37-8"><a href="etltidyverse.html#cb37-8" tabindex="-1"></a>  <span class="fu">group_by</span>(DECADE) <span class="sc">%&gt;%</span> </span>
<span id="cb37-9"><a href="etltidyverse.html#cb37-9" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">media_acres =</span> <span class="fu">mean</span>(TOTALACRES),</span>
<span id="cb37-10"><a href="etltidyverse.html#cb37-10" tabindex="-1"></a>            <span class="at">ds_acres =</span> <span class="fu">sd</span>(TOTALACRES),</span>
<span id="cb37-11"><a href="etltidyverse.html#cb37-11" tabindex="-1"></a>            <span class="at">mediana_acres =</span> <span class="fu">median</span>(TOTALACRES),</span>
<span id="cb37-12"><a href="etltidyverse.html#cb37-12" tabindex="-1"></a>            <span class="at">RIC_acres =</span> <span class="fu">IQR</span>(TOTALACRES),</span>
<span id="cb37-13"><a href="etltidyverse.html#cb37-13" tabindex="-1"></a>            <span class="at">min_acres =</span> <span class="fu">min</span>(TOTALACRES),</span>
<span id="cb37-14"><a href="etltidyverse.html#cb37-14" tabindex="-1"></a>            <span class="at">max_acres =</span> <span class="fu">max</span>(TOTALACRES),</span>
<span id="cb37-15"><a href="etltidyverse.html#cb37-15" tabindex="-1"></a>            <span class="at">q1_acres =</span> <span class="fu">quantile</span>(TOTALACRES)[<span class="dv">2</span>],</span>
<span id="cb37-16"><a href="etltidyverse.html#cb37-16" tabindex="-1"></a>            <span class="at">q3_acres =</span> <span class="fu">quantile</span>(TOTALACRES)[<span class="dv">4</span>]) <span class="ot">-&gt;</span> df_sol_2</span>
<span id="cb37-17"><a href="etltidyverse.html#cb37-17" tabindex="-1"></a></span>
<span id="cb37-18"><a href="etltidyverse.html#cb37-18" tabindex="-1"></a><span class="co"># Vista rápida</span></span>
<span id="cb37-19"><a href="etltidyverse.html#cb37-19" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">head</span>(df_sol_2))</span></code></pre></div>
</details>
<table>
<colgroup>
<col width="10%" />
<col width="12%" />
<col width="9%" />
<col width="15%" />
<col width="10%" />
<col width="10%" />
<col width="10%" />
<col width="9%" />
<col width="9%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">DECADE</th>
<th align="right">media_acres</th>
<th align="right">ds_acres</th>
<th align="right">mediana_acres</th>
<th align="right">RIC_acres</th>
<th align="right">min_acres</th>
<th align="right">max_acres</th>
<th align="right">q1_acres</th>
<th align="right">q3_acres</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">1980-1989</td>
<td align="right">8128.645</td>
<td align="right">23681.53</td>
<td align="right">2887.5</td>
<td align="right">5074.50</td>
<td align="right">1000</td>
<td align="right">427680.0</td>
<td align="right">1543.25</td>
<td align="right">6617.75</td>
</tr>
<tr class="even">
<td align="left">1990-1999</td>
<td align="right">8333.036</td>
<td align="right">18212.44</td>
<td align="right">2925.0</td>
<td align="right">5641.80</td>
<td align="right">1000</td>
<td align="right">231389.0</td>
<td align="right">1545.00</td>
<td align="right">7186.80</td>
</tr>
<tr class="odd">
<td align="left">2000-2009</td>
<td align="right">12329.181</td>
<td align="right">30156.35</td>
<td align="right">3653.5</td>
<td align="right">7859.75</td>
<td align="right">1000</td>
<td align="right">590620.0</td>
<td align="right">1803.00</td>
<td align="right">9662.75</td>
</tr>
<tr class="even">
<td align="left">2010-2016</td>
<td align="right">14443.197</td>
<td align="right">39272.14</td>
<td align="right">3926.0</td>
<td align="right">8552.00</td>
<td align="right">1000</td>
<td align="right">558198.3</td>
<td align="right">1782.00</td>
<td align="right">10334.00</td>
</tr>
</tbody>
</table>
<div class="admon-box ejercicio">
<div class="admon-title">
<span class="icon"></span> Ejercicio 1 para entregar
</div>
<p>
A partir del dataset <code>df</code>, el cual trata de los incendios forestales, realice las siguientes tareas:
</p>
<ol>
<li>
Filtrar los registros para incluir únicamente los incendios ocurridos en el estado de <strong>Idaho</strong>.
</li>
<li>
Seleccionar únicamente las columnas <code>YEAR_</code>, <code>CAUSE</code> y <code>TOTALACRES</code>.
</li>
<li>
Renombrar estas columnas con nombres más claros y descriptivos.
</li>
<li>
Agrupar la información por <code>CAUSE</code> y <code>YEAR_</code>.
</li>
<li>
Resumir el total de acres quemados para cada combinación de causa y año.
</li>
<li>
Elaborar una visualización que muestre los resultados de manera clara.
</li>
</ol>
</div>
<div class="admon-box ejercicio">
<div class="admon-title">
<span class="icon"></span> Ejercicio 2 para entregar
</div>
<p>
Trabajaremos con el conjunto de datos de 120 años de historia olímpica adquirido por Randi Griffin en
<em><a href="https://www.sports-reference.com/">Randi-Griffin</a></em> y puesto a disposición en <em><a href="https://raw.githubusercontent.com/cdeoroaguado/Datos/refs/heads/main/dataviz/athlete_events.csv">athlete_events</a></em>.<br />
Su tarea consiste en identificar los cinco deportes más importantes según el mayor número de medallas otorgadas en el año 2016,
y luego realizar el siguiente análisis:
</p>
<ol>
<li>
Genere una tabla que indique el número de medallas concedidas en cada uno de los cinco principales deportes en 2016.
</li>
<li>
Elabore una tabla que muestre la distribución de la edad de los ganadores de medallas en los cinco principales deportes en 2016.
</li>
<li>
Identifique qué equipos nacionales ganaron el mayor número de medallas en los cinco principales deportes en 2016.
</li>
<li>
Presente un resumen de la tendencia del peso de los atletas masculinos y femeninos ganadores en los cinco principales deportes en 2016.
</li>
</ol>
</div>
</div>
</div>
<div id="ordenación-de-datos" class="section level2 hasAnchor" number="2.4">
<h2><span class="header-section-number">2.4</span> Ordenación de datos<a href="#ordenaci%C3%B3n-de-datos" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>La ordenación de datos es una forma coherente de organizar los datos en R y puede facilitarse a través del paquete <code>tidyr</code> que se encuentra en el ecosistema <code>tidyverse</code>.<br />
Hay tres reglas que podemos seguir para hacer un conjunto de datos ordenado:</p>
<div class="admon-box nota">
<div class="admon-title">
<span class="icon"></span> Reglas de datos ordenados
</div>
<ul>
<li>
<b>Cada variable</b> debe tener su propia columna.
</li>
<li>
<b>Cada observación</b> debe tener su propia fila.
</li>
<li>
<b>Cada valor</b> debe tener su propia celda.
</li>
</ul>
</div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:figura1"></span>
<img src="images/figura1.png" alt="Partes de los datos" width="100%" />
<p class="caption">
Figura 2.5: Partes de los datos
</p>
</div>
<ul>
<li>En primer lugar, tener una estructura de datos consistente es muy importante.<br />
</li>
<li>Los paquetes que forman parte de <code>tidyverse</code> (incluyendo <code>dplyr</code> y <code>ggplot2</code>) están diseñados para trabajar con datos ordenados.</li>
</ul>
<div class="admon-box observacion">
<div class="admon-title">
<span class="icon"></span> Observación
</div>
<p>
<i>Asegurar que tus datos sean uniformes facilita el procesamiento eficiente de tus datos.</i>
</p>
</div>
<ul>
<li><p>Además, colocar las variables en columnas permite facilitar la vectorización en <strong>R</strong>.</p></li>
<li><p>Muchos de los conjuntos de datos que encuentre no estarán ordenados y requerirán algo de trabajo por su parte.<br />
Puede haber muchas razones por las que un conjunto de datos no esté ordenado.<br />
A menudo, <strong>las personas que crearon el conjunto de datos no están familiarizadas con los principios de los datos ordenados</strong>.</p></li>
<li><p>Otra razón común por la que los conjuntos de datos no están ordenados es que los datos se organizan a menudo para facilitar algo más que el análisis.</p></li>
</ul>
<div class="admon-box nota">
<div class="admon-title">
<span class="icon"></span> Nota importante
</div>
<p>
<i>Para que la introducción de datos sea lo más fácil posible, en ocasiones se suelen organizar los datos de forma poco ordenada.</i><br />
Así, muchos conjuntos de datos requieren algún tipo de ordenación antes de poder empezar el análisis.
</p>
</div>
<ul>
<li><p>El primer paso es averiguar cuáles son las variables y observaciones del conjunto de datos.<br />
Esto le facilitará la comprensión de lo que deben ser las columnas y las filas.</p></li>
<li><p>Además, también tendrá que resolver uno o dos problemas comunes:<br />
deberá <strong>averiguar si una variable está repartida en varias columnas, y si una observación está dispersa en varias filas</strong>.<br />
Estos conceptos se conocen como <strong>reunión</strong> y <strong>dispersión</strong>.</p></li>
</ul>
<div class="admon-box observacion">
<div class="admon-title">
<span class="icon"></span> En esta sección veremos:
</div>
<ul>
<li>
<i>Recopilación</i>
</li>
<li>
<i>Distribución</i>
</li>
<li>
<i>Separación</i>
</li>
<li>
<i>Unión</i>
</li>
</ul>
</div>
<div id="recopilación" class="section level3 hasAnchor" number="2.4.1">
<h3><span class="header-section-number">2.4.1</span> Recopilación<a href="#recopilaci%C3%B3n" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li>Un problema común en muchos conjuntos de datos es que los <strong>nombres de las columnas no son variables sino valores de una variable</strong>.<br />
</li>
<li>En la figura siguiente, las columnas 1999 y 2000 son en realidad valores de la variable <code>YEAR</code>.<br />
</li>
<li><em>Cada fila de la tabla existente representa en realidad dos observaciones</em>.</li>
</ul>
<p>El paquete <code>tidyr</code> puede utilizarse para <strong>reunir estas columnas existentes en una nueva variable</strong>.<br />
En este caso, tenemos que crear una nueva columna llamada <code>YEAR</code> y luego reunir en esta los valores existentes en las columnas 1999 y 2000.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:figura2"></span>
<img src="images/figura2.png" alt="Partes de los datos" width="100%" />
<p class="caption">
Figura 2.6: Partes de los datos
</p>
</div>
<div class="admon-box definicion">
<div class="admon-title">
<span class="icon"></span> Definición de <code>gather()</code>
</div>
<p>
La función <code>gather()</code> del paquete <code>tidyr</code> se utiliza para transformar datos de un formato
<i>ancho</i> (<code>wide</code>) a un formato <i>largo</i> (<code>long</code>).<br />
Su objetivo principal es <b>reunir varias columnas en una sola</b>, creando una nueva variable que identifica
los nombres de las columnas originales y otra que contiene los valores asociados.
</p>
<p>
En otras palabras, <code>gather()</code> permite convertir columnas que representan valores en
<b>filas ordenadas</b>, lo que facilita el análisis de datos bajo los principios de datos ordenados.
</p>
</div>
<div class="admon-box ejemplo">
<div class="admon-title">
<span class="icon"></span> Ejemplo práctico
</div>
<p>
En este ejercicio aprenderás a utilizar la función <code>gather()</code> para realizar la tarea de ordenación de datos.
</p>
<ol>
<li>
Descargue el archivo <b>CountryPopulation.csv</b> localizado en
<a href="https://github.com/cdeoroaguado/Datos/blob/main/datarstudio/RDataSets.zip" target="_blank">RDataSets</a>.
</li>
</ol>
</div>
<p style="text-align: center;">
<strong>Solución</strong>
</p>
<ul>
<li>A continuación, tendrás que <strong>nombrar la variable de la nueva columna</strong>. Esto también se llama la clave <code>key</code>, y en este caso será la variable del año (<code>year</code>). Por último, tendrás que proporcionar el valor <code>value</code>, que es el <strong>nombre de la variable cuyos valores se reparten por las celdas</strong>.</li>
</ul>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:figura3"></span>
<img src="images/figura4.png" alt="Ilustración de la función gather" width="100%" />
<p class="caption">
Figura 2.7: Ilustración de la función gather
</p>
</div>
<ul>
<li>Carguemos los datos</li>
</ul>
<details class=chunk-details open><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="etltidyverse.html#cb38-1" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb38-2"><a href="etltidyverse.html#cb38-2" tabindex="-1"></a></span>
<span id="cb38-3"><a href="etltidyverse.html#cb38-3" tabindex="-1"></a>df <span class="ot">=</span> <span class="fu">read_csv</span>(<span class="st">&quot;data/CountryPopulation.csv&quot;</span>)</span>
<span id="cb38-4"><a href="etltidyverse.html#cb38-4" tabindex="-1"></a><span class="fu">head</span>(df,<span class="at">n=</span><span class="dv">5</span>)</span></code></pre></div>
</details>
<pre><code>## # A tibble: 5 × 10
##   `Country Name` `Country Code` `2010` `2011` `2012` `2013` `2014` `2015` `2016`
##   &lt;chr&gt;          &lt;chr&gt;           &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
## 1 Aruba          ABW            1.02e5 1.02e5 1.03e5 1.03e5 1.04e5 1.04e5 1.05e5
## 2 Afghanistan    AFG            2.88e7 2.97e7 3.07e7 3.17e7 3.28e7 3.37e7 3.47e7
## 3 Angola         AGO            2.34e7 2.42e7 2.51e7 2.60e7 2.69e7 2.79e7 2.88e7
## 4 Albania        ALB            2.91e6 2.91e6 2.90e6 2.90e6 2.89e6 2.88e6 2.88e6
## 5 Andorra        AND            8.44e4 8.38e4 8.24e4 8.08e4 7.92e4 7.80e4 7.73e4
## # ℹ 1 more variable: `2017` &lt;dbl&gt;</code></pre>
<ul>
<li>Utilice la función <code>gather</code> como se ve a continuación</li>
</ul>
<details class=chunk-details open><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="etltidyverse.html#cb40-1" tabindex="-1"></a>df2 <span class="ot">=</span> <span class="fu">gather</span>(df, </span>
<span id="cb40-2"><a href="etltidyverse.html#cb40-2" tabindex="-1"></a>                <span class="st">&quot;2010&quot;</span>, <span class="st">&quot;2011&quot;</span>, <span class="st">&quot;2012&quot;</span>, <span class="st">&quot;2013&quot;</span>, <span class="st">&quot;2014&quot;</span>, <span class="st">&quot;2015&quot;</span>, <span class="st">&quot;2016&quot;</span>, <span class="st">&quot;2017&quot;</span>, </span>
<span id="cb40-3"><a href="etltidyverse.html#cb40-3" tabindex="-1"></a>                <span class="at">key =</span> <span class="st">&quot;YEAR&quot;</span>, </span>
<span id="cb40-4"><a href="etltidyverse.html#cb40-4" tabindex="-1"></a>                <span class="at">value =</span> <span class="st">&quot;POPULATION&quot;</span>)</span>
<span id="cb40-5"><a href="etltidyverse.html#cb40-5" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">head</span>(df2, <span class="dv">5</span>))</span></code></pre></div>
</details>
<table>
<thead>
<tr class="header">
<th align="left">Country Name</th>
<th align="left">Country Code</th>
<th align="left">YEAR</th>
<th align="right">POPULATION</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Aruba</td>
<td align="left">ABW</td>
<td align="left">2010</td>
<td align="right">101669</td>
</tr>
<tr class="even">
<td align="left">Afghanistan</td>
<td align="left">AFG</td>
<td align="left">2010</td>
<td align="right">28803167</td>
</tr>
<tr class="odd">
<td align="left">Angola</td>
<td align="left">AGO</td>
<td align="left">2010</td>
<td align="right">23369131</td>
</tr>
<tr class="even">
<td align="left">Albania</td>
<td align="left">ALB</td>
<td align="left">2010</td>
<td align="right">2913021</td>
</tr>
<tr class="odd">
<td align="left">Andorra</td>
<td align="left">AND</td>
<td align="left">2010</td>
<td align="right">84449</td>
</tr>
</tbody>
</table>
<ul>
<li>Otra opción también sería la siguiente, cuando contamos con un gran número de columnas de este tipo, debemos usar la <strong>expresiones regulares</strong>.</li>
</ul>
<details class=chunk-details open><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="etltidyverse.html#cb41-1" tabindex="-1"></a>years <span class="ot">&lt;-</span> <span class="fu">colnames</span>(df)[<span class="fu">grep</span>(<span class="st">&quot;^</span><span class="sc">\\</span><span class="st">d{4}$&quot;</span>, <span class="fu">colnames</span>(df))]</span>
<span id="cb41-2"><a href="etltidyverse.html#cb41-2" tabindex="-1"></a></span>
<span id="cb41-3"><a href="etltidyverse.html#cb41-3" tabindex="-1"></a>df2 <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb41-4"><a href="etltidyverse.html#cb41-4" tabindex="-1"></a>  <span class="fu">gather</span>(<span class="at">key =</span> <span class="st">&quot;YEAR&quot;</span>, <span class="at">value =</span> <span class="st">&quot;POPULATION&quot;</span>, <span class="fu">all_of</span>(years))</span>
<span id="cb41-5"><a href="etltidyverse.html#cb41-5" tabindex="-1"></a></span>
<span id="cb41-6"><a href="etltidyverse.html#cb41-6" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">head</span>(df2, <span class="dv">5</span>))</span></code></pre></div>
</details>
<table>
<thead>
<tr class="header">
<th align="left">Country Name</th>
<th align="left">Country Code</th>
<th align="left">YEAR</th>
<th align="right">POPULATION</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Aruba</td>
<td align="left">ABW</td>
<td align="left">2010</td>
<td align="right">101669</td>
</tr>
<tr class="even">
<td align="left">Afghanistan</td>
<td align="left">AFG</td>
<td align="left">2010</td>
<td align="right">28803167</td>
</tr>
<tr class="odd">
<td align="left">Angola</td>
<td align="left">AGO</td>
<td align="left">2010</td>
<td align="right">23369131</td>
</tr>
<tr class="even">
<td align="left">Albania</td>
<td align="left">ALB</td>
<td align="left">2010</td>
<td align="right">2913021</td>
</tr>
<tr class="odd">
<td align="left">Andorra</td>
<td align="left">AND</td>
<td align="left">2010</td>
<td align="right">84449</td>
</tr>
</tbody>
</table>
<ul>
<li><p>Donde, en <em>expresiones regulares</em>, <code>"^\\d{4}$"</code> tiene el siguiente significado:</p>
<ul>
<li><code>^</code> : Representa el inicio de una cadena.<br />
</li>
<li><code>\\d</code> : Representa un dígito.<br />
</li>
<li><code>{4}</code> : Indica que el elemento anterior (<code>\\d</code>, en este caso) debe aparecer exactamente 4 veces.<br />
</li>
<li><code>$</code> : Representa el final de una cadena.</li>
</ul></li>
<li><p>En resumen, <code>"^\\d{4}$"</code> coincide con cualquier <strong>cadena que contenga exactamente 4 dígitos y no contenga ningún otro carácter adicional antes o después de los dígitos</strong>.</p></li>
</ul>
</div>
<div id="distribución" class="section level3 hasAnchor" number="2.4.2">
<h3><span class="header-section-number">2.4.2</span> Distribución<a href="#distribuci%C3%B3n" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="admon-box definicion">
<div class="admon-title">
<span class="icon"></span> Concepto
</div>
<p>
La <b>distribución</b> es el proceso opuesto a la reunión y
<i>se aplica cuando una sola observación está fragmentada en varias filas</i>.<br />
Su objetivo es reorganizar los datos para que cada observación quede contenida en una única fila.
</p>
</div>
<ul>
<li>En el diagrama siguiente, la tabla debería definir una observación de un país por año. Sin embargo, se observa que está repartida en dos filas: una para <code>cases</code> y otra para <code>population</code>.</li>
</ul>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:figura5"></span>
<img src="images/figura5.png" alt="Distribución" width="100%" />
<p class="caption">
Figura 2.8: Distribución
</p>
</div>
<ul>
<li>Para solucionar este problema, podemos utilizar la función <code>spread()</code> del paquete <code>tidyr</code>.</li>
</ul>
<div class="admon-box definicion">
<div class="admon-title">
<span class="icon"></span> Definición: Sintaxis de <code>spread()</code>
</div>
<p>
La función <code>spread()</code> del paquete <code>tidyr</code> se utiliza para transformar un conjunto de datos
de formato <i>largo</i> (<code>long</code>) a formato <i>ancho</i> (<code>wide</code>).<br />
Su propósito es distribuir los valores de una variable en varias columnas.
</p>
<p>
Toma dos parámetros principales:
</p>
<ul>
<li>
<b><code>key</code></b>: columna que contiene los nombres de las variables que se convertirán en nuevas columnas.
</li>
<li>
<b><code>value</code></b>: columna que contiene los valores que se ubicarán en las nuevas celdas.
</li>
</ul>
</div>
<ul>
<li>Instale el paquete <code>devtools</code> y los conjuntos de datos <strong>DSR</strong> utilizando el código que ve a continuación escribiendo en el panel de la consola. Alternativamente, puede utilizar el panel de paquetes para instalar los librerías</li>
</ul>
<details class=chunk-details open><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="etltidyverse.html#cb42-1" tabindex="-1"></a><span class="co"># Instalar </span></span>
<span id="cb42-2"><a href="etltidyverse.html#cb42-2" tabindex="-1"></a><span class="co"># install.packages(&quot;devtools&quot;)</span></span>
<span id="cb42-3"><a href="etltidyverse.html#cb42-3" tabindex="-1"></a><span class="co"># devtools::install_github(&quot;garrettgman/DSR&quot;)</span></span>
<span id="cb42-4"><a href="etltidyverse.html#cb42-4" tabindex="-1"></a><span class="fu">library</span>(devtools)</span></code></pre></div>
</details>
<ul>
<li>Tomemos los datos de <code>table2</code>:</li>
</ul>
<details class=chunk-details open><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="etltidyverse.html#cb43-1" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">head</span>(table2))</span></code></pre></div>
</details>
<table>
<thead>
<tr class="header">
<th align="left">country</th>
<th align="right">year</th>
<th align="left">type</th>
<th align="right">count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Afghanistan</td>
<td align="right">1999</td>
<td align="left">cases</td>
<td align="right">745</td>
</tr>
<tr class="even">
<td align="left">Afghanistan</td>
<td align="right">1999</td>
<td align="left">population</td>
<td align="right">19987071</td>
</tr>
<tr class="odd">
<td align="left">Afghanistan</td>
<td align="right">2000</td>
<td align="left">cases</td>
<td align="right">2666</td>
</tr>
<tr class="even">
<td align="left">Afghanistan</td>
<td align="right">2000</td>
<td align="left">population</td>
<td align="right">20595360</td>
</tr>
<tr class="odd">
<td align="left">Brazil</td>
<td align="right">1999</td>
<td align="left">cases</td>
<td align="right">37737</td>
</tr>
<tr class="even">
<td align="left">Brazil</td>
<td align="right">1999</td>
<td align="left">population</td>
<td align="right">172006362</td>
</tr>
</tbody>
</table>
<ul>
<li>Utilice la función <code>spread()</code> para corregir este problema.</li>
</ul>
<details class=chunk-details open><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="etltidyverse.html#cb44-1" tabindex="-1"></a>table2b <span class="ot">=</span> <span class="fu">spread</span>(table2, <span class="at">key =</span> type, <span class="at">value =</span> count)</span>
<span id="cb44-2"><a href="etltidyverse.html#cb44-2" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">head</span>(table2b))</span></code></pre></div>
</details>
<table>
<thead>
<tr class="header">
<th align="left">country</th>
<th align="right">year</th>
<th align="right">cases</th>
<th align="right">population</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Afghanistan</td>
<td align="right">1999</td>
<td align="right">745</td>
<td align="right">19987071</td>
</tr>
<tr class="even">
<td align="left">Afghanistan</td>
<td align="right">2000</td>
<td align="right">2666</td>
<td align="right">20595360</td>
</tr>
<tr class="odd">
<td align="left">Brazil</td>
<td align="right">1999</td>
<td align="right">37737</td>
<td align="right">172006362</td>
</tr>
<tr class="even">
<td align="left">Brazil</td>
<td align="right">2000</td>
<td align="right">80488</td>
<td align="right">174504898</td>
</tr>
<tr class="odd">
<td align="left">China</td>
<td align="right">1999</td>
<td align="right">212258</td>
<td align="right">1272915272</td>
</tr>
<tr class="even">
<td align="left">China</td>
<td align="right">2000</td>
<td align="right">213766</td>
<td align="right">1280428583</td>
</tr>
</tbody>
</table>
</div>
<div id="separación" class="section level3 hasAnchor" number="2.4.3">
<h3><span class="header-section-number">2.4.3</span> Separación<a href="#separaci%C3%B3n" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Otro caso común es el de dos variables que se colocan en la misma columna. Por ejemplo, la hoja de cálculo siguiente tiene una columna <strong>State-County Name</strong> que en realidad contiene dos variables separadas por una barra.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:figura6"></span>
<img src="images/figura6.png" alt="DataSet" width="100%" />
<p class="caption">
Figura 2.9: DataSet
</p>
</div>
<p>La función <code>separate()</code> puede utilizarse para dividir una columna en varias columnas dividiendo por un separador. Por defecto, la función <code>separate()</code> buscará automáticamente cualquier carácter no alfanumérico o se puede definir un carácter específico (ver <a href="https://www.rdocumentation.org/packages/tidyr/versions/1.3.0/topics/separate">separate()</a>).</p>
<ul>
<li>En la carpeta de <strong>RDataSets</strong> hay un archivo llamado <strong>usco2005.csv</strong>. Abra este archivo, por ejemplo con Microsoft Excel, o algún otro tipo de software de hoja de cálculo. El archivo debería tener un aspecto similar al de la captura de pantalla de abajo.</li>
</ul>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:figura7"></span>
<img src="images/figura7.png" alt="DataSet de usco2005" width="100%" />
<p class="caption">
Figura 2.10: DataSet de usco2005
</p>
</div>
<ul>
<li>Cargue el archivo <strong>usco2005.csv</strong> en <strong>RStudio</strong> escribiendo el código que ve a continuación en el panel de la consola</li>
</ul>
<details class=chunk-details open><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="etltidyverse.html#cb45-1" tabindex="-1"></a>df <span class="ot">=</span> <span class="fu">read_csv</span>(<span class="st">&quot;data/usco2005.csv&quot;</span>)</span>
<span id="cb45-2"><a href="etltidyverse.html#cb45-2" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">head</span>(df, <span class="dv">5</span>))</span></code></pre></div>
</details>
<table>
<thead>
<tr class="header">
<th align="left">STATE</th>
<th align="right">STATEFIPS</th>
<th align="right">COUNTYFIPS</th>
<th align="right">FIPS</th>
<th align="left">State-County Name</th>
<th align="right">TP-TotPop</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">AL</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">1001</td>
<td align="left">Alabama-Autauga County</td>
<td align="right">48.612</td>
</tr>
<tr class="even">
<td align="left">AL</td>
<td align="right">1</td>
<td align="right">3</td>
<td align="right">1003</td>
<td align="left">Alabama-Baldwin County</td>
<td align="right">162.586</td>
</tr>
<tr class="odd">
<td align="left">AL</td>
<td align="right">1</td>
<td align="right">5</td>
<td align="right">1005</td>
<td align="left">Alabama-Barbour County</td>
<td align="right">28.414</td>
</tr>
<tr class="even">
<td align="left">AL</td>
<td align="right">1</td>
<td align="right">7</td>
<td align="right">1007</td>
<td align="left">Alabama-Bibb County</td>
<td align="right">21.516</td>
</tr>
<tr class="odd">
<td align="left">AL</td>
<td align="right">1</td>
<td align="right">9</td>
<td align="right">1009</td>
<td align="left">Alabama-Blount County</td>
<td align="right">55.725</td>
</tr>
</tbody>
</table>
<ul>
<li>Utilice la función <code>separate()</code> para separar el contenido de la columna <strong>State-County Name</strong> en las columnas <strong>StateAbbrev</strong> y <strong>CountyName</strong></li>
</ul>
<details class=chunk-details open><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="etltidyverse.html#cb46-1" tabindex="-1"></a>df2 <span class="ot">=</span> <span class="fu">separate</span>(df, <span class="st">&quot;State-County Name&quot;</span>,<span class="at">into =</span> <span class="fu">c</span>(<span class="st">&quot;StateAbbrev&quot;</span>, <span class="st">&quot;CountyName&quot;</span>))</span>
<span id="cb46-2"><a href="etltidyverse.html#cb46-2" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">head</span>(df2, <span class="dv">5</span>))</span></code></pre></div>
</details>
<table>
<colgroup>
<col width="9%" />
<col width="15%" />
<col width="16%" />
<col width="7%" />
<col width="18%" />
<col width="16%" />
<col width="15%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">STATE</th>
<th align="right">STATEFIPS</th>
<th align="right">COUNTYFIPS</th>
<th align="right">FIPS</th>
<th align="left">StateAbbrev</th>
<th align="left">CountyName</th>
<th align="right">TP-TotPop</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">AL</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">1001</td>
<td align="left">Alabama</td>
<td align="left">Autauga</td>
<td align="right">48.612</td>
</tr>
<tr class="even">
<td align="left">AL</td>
<td align="right">1</td>
<td align="right">3</td>
<td align="right">1003</td>
<td align="left">Alabama</td>
<td align="left">Baldwin</td>
<td align="right">162.586</td>
</tr>
<tr class="odd">
<td align="left">AL</td>
<td align="right">1</td>
<td align="right">5</td>
<td align="right">1005</td>
<td align="left">Alabama</td>
<td align="left">Barbour</td>
<td align="right">28.414</td>
</tr>
<tr class="even">
<td align="left">AL</td>
<td align="right">1</td>
<td align="right">7</td>
<td align="right">1007</td>
<td align="left">Alabama</td>
<td align="left">Bibb</td>
<td align="right">21.516</td>
</tr>
<tr class="odd">
<td align="left">AL</td>
<td align="right">1</td>
<td align="right">9</td>
<td align="right">1009</td>
<td align="left">Alabama</td>
<td align="left">Blount</td>
<td align="right">55.725</td>
</tr>
</tbody>
</table>
</div>
<div id="unión" class="section level3 hasAnchor" number="2.4.4">
<h3><span class="header-section-number">2.4.4</span> Unión<a href="#uni%C3%B3n" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="admon-box definicion">
<div class="admon-title">
<span class="icon"></span> Definición
</div>
<p>
<code>unite()</code> de <code>tidyr</code> <b>combina varias columnas en una sola</b>,
aplicando un separador entre los valores. Es, conceptualmente, la operación inversa de <code>separate()</code>.
</p>
</div>
<div class="admon-box observacion">
<div class="admon-title">
<span class="icon"></span> Parámetros clave
</div>
<ul>
<li>
<b><code>data</code></b>: marco de datos.
</li>
<li>
<b><code>col</code></b>: nombre de la <b>nueva columna</b> combinada.
</li>
<li>
<b><code>…</code></b>: columnas a unir (en el <b>orden</b> deseado).
</li>
<li>
<b><code>sep</code></b>: separador entre valores (por defecto <code>“_“</code>).
</li>
<li>
<b><code>remove</code></b>: si <code>TRUE</code>, elimina las columnas originales.
</li>
<li>
<b><code>na.rm</code></b>: si <code>TRUE</code>, omite <code>NA</code> al unir; si <code>FALSE</code>, el resultado será <code>NA</code> si alguna parte es <code>NA</code>.
</li>
</ul>
<p>
<b>Sintaxis:</b> <code>unite(data, col, …, sep = “_“, remove = TRUE, na.rm = FALSE)</code>
</p>
</div>
<details class=chunk-details open><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="etltidyverse.html#cb47-1" tabindex="-1"></a>df3 <span class="ot">=</span> <span class="fu">unite</span>(df2, State_County_Name, StateAbbrev, CountyName)</span>
<span id="cb47-2"><a href="etltidyverse.html#cb47-2" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">head</span>(df3, <span class="dv">5</span>))</span></code></pre></div>
</details>
<table>
<thead>
<tr class="header">
<th align="left">STATE</th>
<th align="right">STATEFIPS</th>
<th align="right">COUNTYFIPS</th>
<th align="right">FIPS</th>
<th align="left">State_County_Name</th>
<th align="right">TP-TotPop</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">AL</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">1001</td>
<td align="left">Alabama_Autauga</td>
<td align="right">48.612</td>
</tr>
<tr class="even">
<td align="left">AL</td>
<td align="right">1</td>
<td align="right">3</td>
<td align="right">1003</td>
<td align="left">Alabama_Baldwin</td>
<td align="right">162.586</td>
</tr>
<tr class="odd">
<td align="left">AL</td>
<td align="right">1</td>
<td align="right">5</td>
<td align="right">1005</td>
<td align="left">Alabama_Barbour</td>
<td align="right">28.414</td>
</tr>
<tr class="even">
<td align="left">AL</td>
<td align="right">1</td>
<td align="right">7</td>
<td align="right">1007</td>
<td align="left">Alabama_Bibb</td>
<td align="right">21.516</td>
</tr>
<tr class="odd">
<td align="left">AL</td>
<td align="right">1</td>
<td align="right">9</td>
<td align="right">1009</td>
<td align="left">Alabama_Blount</td>
<td align="right">55.725</td>
</tr>
</tbody>
</table>
<div class="admon-box ejercicio">
<div class="admon-title">
<span class="icon"></span> Ejercicio para entregar
</div>
<p>
Considere el conjunto de datos <a href="https://github.com/cdeoroaguado/Datos/blob/main/datapython/us_state_population.tsv">us_state_population.tsv</a> ubicado en la carpeta de datos de Python de github. Repita el procedimiento planteado en cada ítem de esta sección para obtener el nuevo dataframe con las nuevas columnas <code>Year</code> y <code>Population</code>. Realice unión y separación utilizando las columnas <code>State</code> y <code>Code</code>.
</p>
</div>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="intro.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="vizestatico.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": "https://github.com/rstudio/bookdown-demo/edit/master/02-etltidyverse.Rmd",
    "text": "Edit"
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": ["bookdown-demo.pdf", "bookdown-demo.epub"],
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
