<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Capítulo 2 ETL con Tidyverse | Visualización de datos en R</title>
  <meta name="description" content="Notas de clase de dataviz" />
  <meta name="generator" content="bookdown 0.43 and GitBook 2.6.7" />

  <meta property="og:title" content="Capítulo 2 ETL con Tidyverse | Visualización de datos en R" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Notas de clase de dataviz" />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capítulo 2 ETL con Tidyverse | Visualización de datos en R" />
  
  <meta name="twitter:description" content="Notas de clase de dataviz" />
  

<meta name="author" content="Carlos de Oro Aguado" />


<meta name="date" content="2025-08-21" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="intro.html"/>
<link rel="next" href="methods.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/codefolding-lua-1.1/codefolding-lua.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Visualización de datos en R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Asignatura</a>
<ul>
<li class="chapter" data-level="" data-path=""><a href="#justificaci%C3%B3n"><i class="fa fa-check"></i>Justificación</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#objetivo-general-de-la-asignatura"><i class="fa fa-check"></i>Objetivo general de la asignatura</a></li>
<li class="chapter" data-level="" data-path=""><a href="#resultados-de-aprendizaje-objetivos-espec%C3%ADficos"><i class="fa fa-check"></i>Resultados de aprendizaje (Objetivos específicos)</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#temas-de-la-asignatura"><i class="fa fa-check"></i>Temas de la asignatura</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>1</b> Introducción</a>
<ul>
<li class="chapter" data-level="1.1" data-path="02-tidyverse.html"><a href="#introducci%C3%B3n-a-r-y-rstudio"><i class="fa fa-check"></i><b>1.1</b> Introducción a R y RStudio</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="02-tidyverse.html"><a href="#qu%C3%A9-es-r"><i class="fa fa-check"></i><b>1.1.1</b> ¿Qué es R?</a></li>
<li class="chapter" data-level="1.1.2" data-path="02-tidyverse.html"><a href="#qu%C3%A9-es-rstudio"><i class="fa fa-check"></i><b>1.1.2</b> ¿Qué es RStudio?</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="02-tidyverse.html"><a href="#introducci%C3%B3n-a-git-y-github"><i class="fa fa-check"></i><b>1.2</b> Introducción a Git y GitHub</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="02-tidyverse.html"><a href="#qu%C3%A9-es-git"><i class="fa fa-check"></i><b>1.2.1</b> ¿Qué es Git?</a></li>
<li class="chapter" data-level="1.2.2" data-path="02-tidyverse.html"><a href="#qu%C3%A9-es-github"><i class="fa fa-check"></i><b>1.2.2</b> ¿Qué es GitHub?</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="intro.html"><a href="intro.html#pasos-para-publicar-un-libro-bookdown-en-github-pages"><i class="fa fa-check"></i><b>1.3</b> Pasos para publicar un libro <code>bookdown</code> en GitHub Pages</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="02-tidyverse.html"><a href="#video-paso-a-paso-de-la-publicaci%C3%B3n-del-libro-en-github-pages"><i class="fa fa-check"></i><b>1.3.1</b> Video paso a paso de la publicación del libro en GitHub Pages</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="tidyverse.html"><a href="tidyverse.html"><i class="fa fa-check"></i><b>2</b> ETL con Tidyverse</a>
<ul>
<li class="chapter" data-level="2.1" data-path="tidyverse.html"><a href="tidyverse.html#data-frames"><i class="fa fa-check"></i><b>2.1</b> Data Frames</a></li>
<li class="chapter" data-level="2.2" data-path="02-tidyverse.html"><a href="#importaci%C3%B3n-de-datos"><i class="fa fa-check"></i><b>2.2</b> Importación de datos</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="02-tidyverse.html"><a href="#importaci%C3%B3n-de-archivos-csv-con-read.table"><i class="fa fa-check"></i><b>2.2.1</b> Importación de archivos <code>csv</code> con <code>read.table()</code></a></li>
<li class="chapter" data-level="2.2.2" data-path="02-tidyverse.html"><a href="#importaci%C3%B3n-de-archivos-txt-delimitados-por-tabulaci%C3%B3n-con-read.table"><i class="fa fa-check"></i><b>2.2.2</b> Importación de archivos <code>txt</code> delimitados por tabulación con <code>read.table()</code></a></li>
<li class="chapter" data-level="2.2.3" data-path="02-tidyverse.html"><a href="#importaci%C3%B3n-de-archivos-csv-con-read.csv"><i class="fa fa-check"></i><b>2.2.3</b> Importación de archivos <code>csv</code> con <code>read.csv()</code></a></li>
<li class="chapter" data-level="2.2.4" data-path="tidyverse.html"><a href="tidyverse.html#uso-de-readr-de-tidyverse"><i class="fa fa-check"></i><b>2.2.4</b> Uso de <code>readr</code> de tidyverse</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="tidyverse.html"><a href="tidyverse.html#el-paquete-dplyr"><i class="fa fa-check"></i><b>2.3</b> El paquete <code>dplyr</code></a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="methods.html"><a href="methods.html"><i class="fa fa-check"></i><b>3</b> Methods</a>
<ul>
<li class="chapter" data-level="3.1" data-path="methods.html"><a href="methods.html#math-example"><i class="fa fa-check"></i><b>3.1</b> math example</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="applications.html"><a href="applications.html"><i class="fa fa-check"></i><b>4</b> Applications</a>
<ul>
<li class="chapter" data-level="4.1" data-path="applications.html"><a href="applications.html#example-one"><i class="fa fa-check"></i><b>4.1</b> Example one</a></li>
<li class="chapter" data-level="4.2" data-path="applications.html"><a href="applications.html#example-two"><i class="fa fa-check"></i><b>4.2</b> Example two</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="final-words.html"><a href="final-words.html"><i class="fa fa-check"></i><b>5</b> Final Words</a></li>
<li class="chapter" data-level="" data-path="referencias.html"><a href="referencias.html"><i class="fa fa-check"></i>Referencias</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Publicado con bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Visualización de datos en R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="tidyverse" class="section level1 hasAnchor" number="2">
<h1><span class="header-section-number">Capítulo 2</span> ETL con Tidyverse<a href="tidyverse.html#tidyverse" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>El <strong>Tidyverse</strong> es un conjunto de paquetes integrados para el lenguaje de programación R, diseñados con el objetivo de facilitar el análisis de datos de manera estructurada, legible y eficiente. Su filosofía se basa en el concepto de <strong>“datos ordenados” (tidy data)</strong>, donde cada variable es una columna, cada observación una fila, y cada tipo de unidad observacional forma una tabla.</p>
<p>Estos paquetes comparten principios de diseño comunes y una gramática coherente, lo que permite a los usuarios aprender un conjunto de reglas aplicables en todo el ecosistema, aumentando así la productividad y la claridad del código.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:tidy-fig"></span>
<img src="images/tidypacsinfondo.png" alt="Paquetes de tidyverse" width="70%" />
<p class="caption">
Figura 2.1: Paquetes de tidyverse
</p>
</div>
<div id="data-frames" class="section level2 hasAnchor" number="2.1">
<h2><span class="header-section-number">2.1</span> Data Frames<a href="tidyverse.html#data-frames" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="admon-box definicion">
<div class="admon-title">
<span class="icon"></span> Definición
</div>
<p>
Un <strong>data frame</strong> es una estructura de datos clave en estadística y en <strong>R</strong>.
</p>
</div>
<ul>
<li>La estructura básica de un data frame es que <em>hay una observación por fila y cada columna representa una variable, medida, rasgo o característica de esa observación</em>.<br />
</li>
<li><strong>R</strong> tiene una implementación interna de los data frames que probablemente es la que más se utiliza en la práctica.</li>
</ul>
</div>
<div id="importación-de-datos" class="section level2 hasAnchor" number="2.2">
<h2><span class="header-section-number">2.2</span> Importación de datos<a href="#importaci%C3%B3n-de-datos" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="admon-box nota">
<div class="admon-title">
<span class="icon"></span> Fuentes de datos en R
</div>
<p>
Los conjuntos de datos de gran tamaño, generalmente almacenados como <strong>data frames</strong> en <strong>R</strong>, suelen provenir de archivos externos.<br />
Existen múltiples tipos de archivos que pueden importarse, entre ellos:<br />

</p>
<ul>
<li>
<strong>Archivos de texto</strong> en formatos como <code>csv</code>, <code>txt</code>, <code>html</code> y <code>json</code>.
</li>
<li>
Salidas de software estadístico como <strong>SAS</strong> y <strong>SPSS</strong>.
</li>
<li>
Recursos en línea como páginas <strong>html</strong> y servicios web.
</li>
<li>
<strong>Bases de datos relacionales y no relacionales</strong>.
</li>
</ul>
<p>
El ecosistema <strong>Tidyverse</strong> ofrece funciones que permiten importar y gestionar estas diversas fuentes de datos de manera sencilla y eficiente.
</p>
</div>
<div id="importación-de-archivos-csv-con-read.table" class="section level3 hasAnchor" number="2.2.1">
<h3><span class="header-section-number">2.2.1</span> Importación de archivos <code>csv</code> con <code>read.table()</code><a href="#importaci%C3%B3n-de-archivos-csv-con-read.table" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="admon-box definicion">
<div class="admon-title">
<span class="icon"></span> Definición
</div>
<p>
La función <code>read.table()</code> es una función integrada en <strong>R</strong> que permite leer archivos de distintos formatos y convertirlos en un <strong>data frame</strong>.<br />
Es una de las funciones más utilizadas para importar archivos simples en R.
</p>
</div>
<p>La sintaxis de <strong><code>read.table()</code></strong> requiere indicar:<br />
- Un nombre de archivo (ruta de acceso).<br />
- Un valor lógico (<strong><code>TRUE/FALSE</code></strong>) para definir si la primera fila contiene los nombres de las columnas.</p>
<ul>
<li>Si se establece en <strong><code>TRUE</code></strong>, la primera fila se interpreta como encabezado.<br />
</li>
<li>Si se establece en <strong><code>FALSE</code></strong>, las columnas se importan sin nombres definidos.</li>
</ul>
<p>El resultado de la función siempre es un <strong>data frame</strong>.</p>
<p>Una alternativa práctica es la función <strong><code>file.choose()</code></strong>, que permite seleccionar el archivo de manera interactiva sin necesidad de escribir la ruta manualmente.</p>
<div class="admon-box observacion">
<div class="admon-title">
<span class="icon"></span> Observación
</div>
<p>
Pasos para importar un archivo <code>csv</code> con <code>read.table()</code>:
</p>
<ol>
<li>
Abrir <strong>RStudio</strong> y dirigirse a la consola.
</li>
<li>
Establecer el directorio de trabajo con código en la consola o desde el menú:<br>
<em>Sesión → Establecer directorio de trabajo → Elegir directorio</em>.
</li>
<li>
Ejecutar la función <code>read.table()</code> indicando el archivo <code>csv</code> a importar.
</li>
</ol>
</div>
<details class=chunk-details open><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="tidyverse.html#cb1-1" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">&quot;~/Books_CienciaDatos/rbook_dataviz&quot;</span>)</span></code></pre></div>
</details>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:fig-2"></span>
<img src="images/setwd.png" alt="setwd" width="70%" />
<p class="caption">
Figura 2.2: setwd
</p>
</div>
<ul>
<li><p>En la carpeta <strong><a href="https://github.com/cdeoroaguado/Datos/blob/main/datarstudio/RDataSets.zip">RDataSets</a></strong> se encuentra el archivo <strong>StudyArea.csv</strong>, que corresponde a un archivo separado por comas.<br />
Este archivo contiene información sobre incendios forestales ocurridos entre los años 1980 y 2016 en distintos estados de EE. UU., entre ellos: California, Oregón, Washington, Idaho, Montana, Wyoming, Colorado, Utah, Nevada, Arizona y Nuevo México.</p></li>
<li><p>El archivo incluye más de <strong>439000 registros</strong> distribuidos en <strong>37 columnas</strong>, que describen las características de cada incendio durante ese periodo.</p></li>
<li><p>Para cargar estos datos en un nuevo objeto <strong>data frame</strong>, puede utilizarse la función <code>read.table()</code> de la siguiente manera:</p></li>
</ul>
<details class=chunk-details open><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="tidyverse.html#cb2-1" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">&quot;data/StudyArea.csv&quot;</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
</details>
<ul>
<li>Recibirá un mensaje de error cuando intente ejecutar esta línea de código. El mensaje de error mensaje de error debería aparecer como se ve a continuación</li>
</ul>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:fig-3"></span>
<img src="images/error.png" alt="error en rmd" width="70%" />
<p class="caption">
Figura 2.3: error en rmd
</p>
</div>
<ul>
<li>La razón por la que se generó un mensaje de error en este caso es que la función <strong><code>read.table()</code></strong> utiliza espacios como delimitador entre registros y nuestro archivo utiliza comas como delimitador</li>
</ul>
<p>Actualice su llamada a <strong><code>read.table()</code></strong> como se ve a continuación para incluir el argumento <strong><code>sep</code></strong>, que debería ser una coma</p>
<details class=chunk-details open><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="tidyverse.html#cb3-1" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">&quot;data/StudyArea.csv&quot;</span>, <span class="at">sep=</span><span class="st">&quot;,&quot;</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
</details>
<ul>
<li>Cuando ejecute esta línea de código verá un nuevo error</li>
</ul>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:fig-4"></span>
<img src="images/error2.png" alt="continuación del error en rmd" width="70%" />
<p class="caption">
Figura 2.4: continuación del error en rmd
</p>
</div>
<ul>
<li>La función <code>read.table()</code> no completa de manera automática las celdas vacías con un valor por defecto como <code>NA</code>.<br />
Por este motivo, si alguna fila del archivo no contiene el número esperado de columnas (en este caso, 14), se genera un mensaje de error durante la importación.</li>
</ul>
<p>Para solucionar este inconveniente, puede añadirse el parámetro <code>fill = TRUE</code>, lo que permite a <strong>R</strong> rellenar los espacios vacíos con <code>NA</code> y mantener la estructura correcta del <code>data.frame</code>.</p>
<details class=chunk-details open><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="tidyverse.html#cb4-1" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">&quot;data/StudyArea.csv&quot;</span>, </span>
<span id="cb4-2"><a href="tidyverse.html#cb4-2" tabindex="-1"></a>                 <span class="at">header =</span> <span class="cn">TRUE</span>, </span>
<span id="cb4-3"><a href="tidyverse.html#cb4-3" tabindex="-1"></a>                 <span class="at">fill   =</span> <span class="cn">TRUE</span>, </span>
<span id="cb4-4"><a href="tidyverse.html#cb4-4" tabindex="-1"></a>                 <span class="at">sep    =</span> <span class="st">&quot;,&quot;</span>)</span>
<span id="cb4-5"><a href="tidyverse.html#cb4-5" tabindex="-1"></a><span class="fu">nrow</span>(df)</span></code></pre></div>
</details>
<pre><code>## [1] 153095</code></pre>
<ul>
<li><p>Al ejecutar esta instrucción, el contenido del archivo se importa a un objeto de tipo <strong>data frame</strong>. Sin embargo, al revisar la pestaña <strong>Global Environment</strong> en <strong>RStudio</strong>, se observa que solo se han cargado <strong>153095 registros</strong>, a pesar de que el archivo original contiene más de <strong>400000</strong>.</p></li>
<li><p>La causa de esta diferencia suele estar en el manejo de las <strong>comillas (simples o dobles)</strong> presentes dentro del archivo <code>csv</code>, las cuales pueden interrumpir la lectura y provocar que algunos registros sean descartados.</p></li>
</ul>
<p>Para corregir este problema, se debe añadir el parámetro <code>quote = ""</code>, que le indica a <strong>R</strong> que ignore las comillas y procese correctamente todas las filas del archivo.</p>
<details class=chunk-details open><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="tidyverse.html#cb6-1" tabindex="-1"></a>df <span class="ot">=</span> <span class="fu">read.table</span>(<span class="st">&quot;data/StudyArea.csv&quot;</span>, </span>
<span id="cb6-2"><a href="tidyverse.html#cb6-2" tabindex="-1"></a>                <span class="at">header=</span><span class="cn">TRUE</span>, </span>
<span id="cb6-3"><a href="tidyverse.html#cb6-3" tabindex="-1"></a>                <span class="at">fill=</span><span class="cn">TRUE</span>, </span>
<span id="cb6-4"><a href="tidyverse.html#cb6-4" tabindex="-1"></a>                <span class="at">quote=</span><span class="st">&quot;</span><span class="sc">\&quot;</span><span class="st">&quot;</span>, </span>
<span id="cb6-5"><a href="tidyverse.html#cb6-5" tabindex="-1"></a>                <span class="at">sep=</span><span class="st">&quot;,&quot;</span>)</span>
<span id="cb6-6"><a href="tidyverse.html#cb6-6" tabindex="-1"></a><span class="fu">nrow</span>(df)</span></code></pre></div>
</details>
<pre><code>## [1] 439362</code></pre>
<ul>
<li>Al ejecutar esta línea de código, se deberían importar <strong>440476 registros</strong>. Los datos se cargan en un objeto de tipo <strong>R data.frame</strong>, que es una estructura similar a una tabla. Por ahora, puede pensarse en ellos como tablas que contienen columnas y filas.</li>
</ul>
<div class="admon-box observacion">
<div class="admon-title">
<span class="icon"></span> Observación
</div>
<p>
<p>La función <code>read.table()</code> se utiliza normalmente para cargar archivos de texto delimitados por tabulaciones.</p>
Sin embargo, muchas personas intentan emplearla directamente con archivos en formato <code>csv</code> sin especificar los parámetros adecuados, lo que puede generar errores en la importación.<br />
Una alternativa más práctica es usar la función <code>read.csv()</code>, como veremos en el siguiente paso.
</p>
</div>
</div>
<div id="importación-de-archivos-txt-delimitados-por-tabulación-con-read.table" class="section level3 hasAnchor" number="2.2.2">
<h3><span class="header-section-number">2.2.2</span> Importación de archivos <code>txt</code> delimitados por tabulación con <code>read.table()</code><a href="#importaci%C3%B3n-de-archivos-txt-delimitados-por-tabulaci%C3%B3n-con-read.table" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><p>La función <code>read.table()</code> se utiliza con frecuencia para leer el contenido de archivos delimitados por tabulaciones u otros separadores. En este ejemplo, se trabajará con el archivo <strong>all_genes_pombase.txt</strong>, ubicado en la carpeta <strong><a href="https://github.com/cdeoroaguado/Datos/blob/main/datarstudio/RDataSets.zip">RDataSets</a></strong>.</p></li>
<li><p>Antes de importarlo en <strong>R</strong>, se recomienda abrir el archivo en <strong>Excel</strong> o en cualquier editor de texto para observar su estructura, campos y delimitadores.</p></li>
<li><p>Una vez identificado el formato del archivo, en la consola de <strong>R</strong> puedes ejecutar el siguiente código para realizar la importación:</p></li>
</ul>
<details class=chunk-details open><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="tidyverse.html#cb8-1" tabindex="-1"></a><span class="co"># Lectura de archivo delimitado por tabulaciones</span></span>
<span id="cb8-2"><a href="tidyverse.html#cb8-2" tabindex="-1"></a>genes <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">&quot;data/all_genes_pombase.txt&quot;</span>, </span>
<span id="cb8-3"><a href="tidyverse.html#cb8-3" tabindex="-1"></a>                    <span class="at">header =</span> <span class="cn">TRUE</span>,       </span>
<span id="cb8-4"><a href="tidyverse.html#cb8-4" tabindex="-1"></a>                    <span class="at">sep =</span> <span class="st">&quot;</span><span class="sc">\t</span><span class="st">&quot;</span>,          </span>
<span id="cb8-5"><a href="tidyverse.html#cb8-5" tabindex="-1"></a>                    <span class="at">quote=</span><span class="st">&quot;</span><span class="sc">\&quot;</span><span class="st">&quot;</span>)  </span>
<span id="cb8-6"><a href="tidyverse.html#cb8-6" tabindex="-1"></a><span class="co"># numero de filas</span></span>
<span id="cb8-7"><a href="tidyverse.html#cb8-7" tabindex="-1"></a><span class="fu">nrow</span>(genes)</span></code></pre></div>
</details>
<pre><code>## [1] 7019</code></pre>
<details class=chunk-details open><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="tidyverse.html#cb10-1" tabindex="-1"></a><span class="co"># Visualizar las primeras filas</span></span>
<span id="cb10-2"><a href="tidyverse.html#cb10-2" tabindex="-1"></a><span class="fu">head</span>(genes)</span></code></pre></div>
</details>
<pre><code>##     ensembl_id        name chromosome
## 1  SPAC1002.01 SPAC1002.01          I
## 2  SPAC1002.02       pom34          I
## 3 SPAC1002.03c        gls2          I
## 4 SPAC1002.04c       taf11          I
## 5 SPAC1002.05c        jmj2          I
## 6 SPAC1002.06c        bqt2          I
##                                                     description   feature_type
## 1                                     conserved fungal protein  protein_coding
## 2                                            nucleoporin Pom34  protein_coding
## 3                            glucosidase II alpha subunit Gls2  protein_coding
## 4 transcription factor TFIID complex subunit Taf11 (predicted)  protein_coding
## 5                                     histone demethylase Jmj2  protein_coding
## 6                               bouquet formation protein Bqt2  protein_coding
##   strand   start     end
## 1      1 1798347 1799015
## 2      1 1799061 1800053
## 3     -1 1799915 1803141
## 4     -1 1803624 1804491
## 5     -1 1804548 1806797
## 6     -1 1807270 1807781</code></pre>
<p>Esto permitirá cargar <strong>7019 registros</strong> en un objeto <code>data.frame</code>. Es importante tener en cuenta que, aunque la función realiza la importación, <strong>varios de sus parámetros deben configurarse adecuadamente al momento de leer el dataset</strong>, lo que hace que el proceso no sea tan directo ni automático como podría suponerse inicialmente.</p>
</div>
<div id="importación-de-archivos-csv-con-read.csv" class="section level3 hasAnchor" number="2.2.3">
<h3><span class="header-section-number">2.2.3</span> Importación de archivos <code>csv</code> con <code>read.csv()</code><a href="#importaci%C3%B3n-de-archivos-csv-con-read.csv" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="admon-box definicion">
<div class="admon-title">
<span class="icon"></span> Definición: <code>read.csv()</code>
</div>
<p>
La función <code>read.csv()</code> es una función incorporada en <strong>R</strong> que permite importar archivos delimitados por comas (<code>csv</code>) de manera sencilla.<br />
Está diseñada específicamente para este tipo de archivos y establece de forma predeterminada el argumento
<code>header = TRUE</code> (la primera fila se toma como nombres de columna) y <code>sep = “,”</code>
(coma como delimitador de campos).<br />
Esto hace que <code>read.csv()</code> sea una de las formas más rápidas y eficientes de cargar datos en <strong>R</strong> cuando provienen de archivos <code>csv</code>.
</p>
</div>
<ul>
<li><p>La función <code>read.csv()</code> es una función incorporada en <strong>R</strong> que resulta casi idéntica a <code>read.table()</code>. La principal diferencia es que en <code>read.csv()</code> los argumentos de <strong>cabecera</strong> y <strong>relleno</strong> se establecen en <code>TRUE</code> por defecto, lo que facilita la carga de archivos delimitados por comas (<code>csv</code>). En este punto, se observa que usar <code>read.csv()</code> implifica notablemente el proceso de importación.</p></li>
<li><p>A diferencia de <code>read.table()</code>, la función <code>read.csv()</code> <strong>gestiona automáticamente la mayoría de las configuraciones necesarias</strong> al leer un archivo <code>csv</code>. Esto permite cargar correctamente incluso archivos con más de <strong>400000 registros</strong> sin tener que especificar tantos parámetros manualmente.</p></li>
</ul>
<details class=chunk-details open><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="tidyverse.html#cb12-1" tabindex="-1"></a><span class="co"># Lectura de archivo CSV con read.csv()</span></span>
<span id="cb12-2"><a href="tidyverse.html#cb12-2" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;data/StudyArea.csv&quot;</span>)</span>
<span id="cb12-3"><a href="tidyverse.html#cb12-3" tabindex="-1"></a></span>
<span id="cb12-4"><a href="tidyverse.html#cb12-4" tabindex="-1"></a><span class="co"># numero de fila</span></span>
<span id="cb12-5"><a href="tidyverse.html#cb12-5" tabindex="-1"></a><span class="fu">nrow</span>(df)</span></code></pre></div>
</details>
<pre><code>## [1] 439362</code></pre>
</div>
<div id="uso-de-readr-de-tidyverse" class="section level3 hasAnchor" number="2.2.4">
<h3><span class="header-section-number">2.2.4</span> Uso de <code>readr</code> de tidyverse<a href="tidyverse.html#uso-de-readr-de-tidyverse" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="admon-box definicion">
<div class="admon-title">
<span class="icon"></span> Definición: <code>readr</code>
</div>
<p>
<code>readr</code> es el paquete del ecosistema <strong>tidyverse</strong> para lectura y escritura rápida de datos tabulares.
Produce objetos <code>tibble</code>, maneja de forma estable codificaciones (UTF-8), tipos de columna y valores perdidos, e
incluye herramientas para diagnosticar problemas de importación. Su API es consistente, minimalista y pensada para flujos
reproducibles.
</p>
</div>
<div class="admon-box ventaja">
<div class="admon-title">
<span class="icon"></span> Ventajas claves
</div>
<ol>
<li>
<strong>Velocidad y consistencia</strong> en lectura/escritura de archivos delimitados.
</li>
<li>
<strong>Tipos de columnas explícitos</strong> con <code>col_types</code> y funciones <code>col_*</code>.
</li>
<li>
<strong>Diagnóstico</strong> con <code>spec()</code> y <code>problems()</code>.
</li>
<li>
<strong>Salida en <code>tibble</code></strong> (imprime y maneja mejor columnas anchas/fechas).
</li>
<li>
<strong>Soporte de locales</strong> (<code>locale()</code>) para decimales, fechas, codificación, etc.
</li>
</ol>
</div>
<div class="admon-box observacion">
<div class="admon-title">
<span class="icon"></span> Funciones principales de lectura
</div>
<p>
<table>
<colgroup>
<col width="22%" />
<col width="43%" />
<col width="33%" />
</colgroup>
<thead>
<tr class="header">
<th>Función</th>
<th>Propósito</th>
<th>Formato/Delimitador</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>read_csv()</code></td>
<td><code>csv</code> con punto como decimal</td>
<td><code>,</code></td>
</tr>
<tr class="even">
<td><code>read_csv2()</code></td>
<td><code>csv</code> europeo (coma decimal)</td>
<td><code>;</code></td>
</tr>
<tr class="odd">
<td><code>read_tsv()</code></td>
<td>Valores separados por tabulador</td>
<td><code>\t</code></td>
</tr>
<tr class="even">
<td><code>read_delim(delim=)</code></td>
<td>Delimitador personalizado</td>
<td>Cualquiera (p. ej. <code>\|</code>, <code>:</code>)</td>
</tr>
<tr class="odd">
<td><code>read_table()</code></td>
<td>Columnas separadas por espacios</td>
<td>Espacios en blanco</td>
</tr>
<tr class="even">
<td><code>read_fwf()</code></td>
<td>Formato de ancho fijo</td>
<td>Anchos/posiciones</td>
</tr>
<tr class="odd">
<td><code>read_lines()</code></td>
<td>Leer líneas como vector de caracteres</td>
<td>Texto</td>
</tr>
<tr class="even">
<td><code>read_file()</code></td>
<td>Leer archivo completo como cadena única</td>
<td>Texto</td>
</tr>
<tr class="odd">
<td><code>read_rds()</code></td>
<td>Leer archivo R serializado</td>
<td><code>.rds</code></td>
</tr>
</tbody>
</table>
</p>
</div>
<div class="admon-box observacion">
<div class="admon-title">
<span class="icon"></span> Funciones de escritura
</div>
<p>
<table>
<thead>
<tr class="header">
<th>Función</th>
<th>Propósito</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>write_csv()</code></td>
<td>Escribir <code>csv</code> (punto decimal)</td>
</tr>
<tr class="even">
<td><code>write_csv2()</code></td>
<td>Escribir <code>csv</code> (coma decimal)</td>
</tr>
<tr class="odd">
<td><code>write_tsv()</code></td>
<td>Escribir delimitado por tabulador</td>
</tr>
<tr class="even">
<td><code>write_delim()</code></td>
<td>Escribir con delimitador personalizado</td>
</tr>
<tr class="odd">
<td><code>write_rds()</code></td>
<td>Guardar objeto R en <code>.rds</code></td>
</tr>
</tbody>
</table>
</p>
</div>
<div class="admon-box observacion">
<div class="admon-title">
<span class="icon"></span> Argumentos comunes (lectura)
</div>
<p>
<table>
<colgroup>
<col width="13%" />
<col width="58%" />
<col width="27%" />
</colgroup>
<thead>
<tr class="header">
<th>Argumento</th>
<th>Qué controla</th>
<th>Ejemplo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>col_types</code></td>
<td>Tipos de columnas (explícitos)</td>
<td><code>col_types = cols(id = col_integer())</code></td>
</tr>
<tr class="even">
<td><code>na</code></td>
<td>Cadenas que se tratarán como NA</td>
<td><code>na = c("", "NA", "NULL")</code></td>
</tr>
<tr class="odd">
<td><code>locale</code></td>
<td>Configuración regional (decimal, fecha, tz, encoding)</td>
<td><code>locale(decimal_mark = ",")</code></td>
</tr>
<tr class="even">
<td><code>skip</code> / <code>n_max</code></td>
<td>Filas a omitir / máximo de filas a leer</td>
<td><code>skip = 2, n_max = 1e5</code></td>
</tr>
<tr class="odd">
<td><code>comment</code></td>
<td>Prefijo de comentario para ignorar líneas</td>
<td><code>comment = "#"</code></td>
</tr>
<tr class="even">
<td><code>guess_max</code></td>
<td>Filas usadas para “adivinar” tipos</td>
<td><code>guess_max = 100000</code></td>
</tr>
<tr class="odd">
<td><code>show_col_types</code></td>
<td>Muestra la conjetura de tipos al leer</td>
<td><code>show_col_types = FALSE</code></td>
</tr>
</tbody>
</table>
<blockquote>
<p><strong>Tip</strong>: cuando los tipos son críticos, <strong>no confíes solo en la inferencia</strong>: pasa <code>col_types</code> explícito.</p>
</blockquote>
</p>
</div>
<ul>
<li>Veamos el siguiente ejemplo. Carguemos los siguientes datos:</li>
</ul>
<details class=chunk-details open><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="tidyverse.html#cb14-1" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb14-2"><a href="tidyverse.html#cb14-2" tabindex="-1"></a></span>
<span id="cb14-3"><a href="tidyverse.html#cb14-3" tabindex="-1"></a><span class="co"># CSV con punto decimal y encabezados</span></span>
<span id="cb14-4"><a href="tidyverse.html#cb14-4" tabindex="-1"></a>dfReadr <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;data/StudyArea.csv&quot;</span>,           </span>
<span id="cb14-5"><a href="tidyverse.html#cb14-5" tabindex="-1"></a>  <span class="at">col_types =</span> <span class="fu">cols</span>(<span class="at">.default =</span> <span class="st">&quot;c&quot;</span>),  <span class="co"># Columnas (.default) como &quot;character&quot;</span></span>
<span id="cb14-6"><a href="tidyverse.html#cb14-6" tabindex="-1"></a>  <span class="at">col_names =</span> <span class="cn">TRUE</span>)                  <span class="co"># la 1ra fila como nombres de las columnas</span></span>
<span id="cb14-7"><a href="tidyverse.html#cb14-7" tabindex="-1"></a></span>
<span id="cb14-8"><a href="tidyverse.html#cb14-8" tabindex="-1"></a><span class="fu">head</span>(dfReadr)</span></code></pre></div>
</details>
<pre><code>## # A tibble: 6 × 14
##   FID   ORGANIZATI UNIT  SUBUNIT SUBUNIT2        FIRENAME CAUSE YEAR_ STARTDATED
##   &lt;chr&gt; &lt;chr&gt;      &lt;chr&gt; &lt;chr&gt;   &lt;chr&gt;           &lt;chr&gt;    &lt;chr&gt; &lt;chr&gt; &lt;chr&gt;     
## 1 0     FWS        81682 USCADBR San Diego Bay … PUMP HO… Human 2001  1/1/01 0:…
## 2 1     FWS        81682 USCADBR San Diego Bay … I5       Human 2002  5/3/02 0:…
## 3 2     FWS        81682 USCADBR San Diego Bay … SOUTHBAY Human 2002  6/1/02 0:…
## 4 3     FWS        81682 USCADBR San Diego Bay … MARINA   Human 2001  7/12/01 0…
## 5 4     FWS        81682 USCADBR San Diego Bay … HILL     Human 1994  9/13/94 0…
## 6 5     FWS        81682 USCADBR San Diego Bay … IRRIGAT… Human 1994  4/22/94 0…
## # ℹ 5 more variables: CONTRDATED &lt;chr&gt;, OUTDATED &lt;chr&gt;, STATE &lt;chr&gt;,
## #   STATE_FIPS &lt;chr&gt;, TOTALACRES &lt;chr&gt;</code></pre>
<details class=chunk-details open><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="tidyverse.html#cb16-1" tabindex="-1"></a><span class="fu">spec</span>(dfReadr)         <span class="co"># Esquema de tipos</span></span></code></pre></div>
</details>
<pre><code>## cols(
##   .default = col_character(),
##   FID = col_character(),
##   ORGANIZATI = col_character(),
##   UNIT = col_character(),
##   SUBUNIT = col_character(),
##   SUBUNIT2 = col_character(),
##   FIRENAME = col_character(),
##   CAUSE = col_character(),
##   YEAR_ = col_character(),
##   STARTDATED = col_character(),
##   CONTRDATED = col_character(),
##   OUTDATED = col_character(),
##   STATE = col_character(),
##   STATE_FIPS = col_character(),
##   TOTALACRES = col_character()
## )</code></pre>
<ul>
<li><p>Al ejecutar nuevamente la función sin el argumento <code>col_types</code>, <strong>R</strong>* intentará detectar automáticamente el tipo de dato de cada columna. En este proceso se mostrará primero un listado con los nombres de las columnas y el tipo asignado a cada una, seguido de un mensaje de advertencia que indica la presencia de errores de análisis durante la importación, lo cual ejemplifica las inconsistencias que pueden surgir al dejar la inferencia de tipos en manos del sistema.</p></li>
<li><p>Actualice el código como se muestra a continuación y ejecútelo nuevamente. En este caso, se especifica que la columna <code>UNIT</code> debe ser importada como un dato de tipo carácter (texto):</p></li>
</ul>
<details class=chunk-details open><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="tidyverse.html#cb18-1" tabindex="-1"></a>dfReadr <span class="ot">=</span> <span class="fu">read_csv</span>(<span class="st">&quot;data/StudyArea.csv&quot;</span>, </span>
<span id="cb18-2"><a href="tidyverse.html#cb18-2" tabindex="-1"></a>                   <span class="at">col_types =</span> <span class="fu">list</span>(<span class="at">FID =</span> <span class="fu">col_character</span>()),</span>
<span id="cb18-3"><a href="tidyverse.html#cb18-3" tabindex="-1"></a>                   <span class="at">col_names =</span> <span class="cn">TRUE</span>)                </span>
<span id="cb18-4"><a href="tidyverse.html#cb18-4" tabindex="-1"></a></span>
<span id="cb18-5"><a href="tidyverse.html#cb18-5" tabindex="-1"></a><span class="fu">head</span>(dfReadr)</span></code></pre></div>
</details>
<pre><code>## # A tibble: 6 × 14
##   FID   ORGANIZATI UNIT  SUBUNIT SUBUNIT2        FIRENAME CAUSE YEAR_ STARTDATED
##   &lt;chr&gt; &lt;chr&gt;      &lt;chr&gt; &lt;chr&gt;   &lt;chr&gt;           &lt;chr&gt;    &lt;chr&gt; &lt;dbl&gt; &lt;chr&gt;     
## 1 0     FWS        81682 USCADBR San Diego Bay … PUMP HO… Human  2001 1/1/01 0:…
## 2 1     FWS        81682 USCADBR San Diego Bay … I5       Human  2002 5/3/02 0:…
## 3 2     FWS        81682 USCADBR San Diego Bay … SOUTHBAY Human  2002 6/1/02 0:…
## 4 3     FWS        81682 USCADBR San Diego Bay … MARINA   Human  2001 7/12/01 0…
## 5 4     FWS        81682 USCADBR San Diego Bay … HILL     Human  1994 9/13/94 0…
## 6 5     FWS        81682 USCADBR San Diego Bay … IRRIGAT… Human  1994 4/22/94 0…
## # ℹ 5 more variables: CONTRDATED &lt;chr&gt;, OUTDATED &lt;chr&gt;, STATE &lt;chr&gt;,
## #   STATE_FIPS &lt;dbl&gt;, TOTALACRES &lt;dbl&gt;</code></pre>
</div>
</div>
<div id="el-paquete-dplyr" class="section level2 hasAnchor" number="2.3">
<h2><span class="header-section-number">2.3</span> El paquete <code>dplyr</code><a href="tidyverse.html#el-paquete-dplyr" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="admon-box definicion">
<div class="admon-title">
<span class="icon"></span> Definición
</div>
<p>
El paquete <strong>dplyr</strong> fue desarrollado por <em>Hadley Wickham</em> de RStudio y es una versión optimizada y destilada de su paquete <strong>plyr</strong>.
</p>
</div>
<ul>
<li>Una importante contribución de <code>dplyr</code> es que proporciona una <strong>gramática</strong> (en particular, <em>verbos</em>) para la <em>manipulación de datos y operación con data frames</em>.<br />
</li>
<li>Con esta gramática se puede comunicar de forma comprensible lo que se está haciendo a un data frame, lo cual es muy útil porque proporciona una abstracción para la manipulación de datos que antes no existía.<br />
</li>
<li>Otra ventaja es que las funciones de <code>dplyr</code> son muy rápidas, ya que muchas operaciones clave están codificadas en <code>C++</code>.</li>
</ul>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="intro.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="methods.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": "https://github.com/rstudio/bookdown-demo/edit/master/02-tidyverse.Rmd",
    "text": "Edit"
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": ["bookdown-demo.pdf", "bookdown-demo.epub"],
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
